### PR TITLE
fix: Propagate deletion of db migrations from Wasp src to the generated project

### LINKED ISSUE #211: Propagate deletion of db migrations from Wasp src to the generated project
Right now, if you delete `migrations/` dir from the Wasp project root dir and run `wasp start` or `wasp build`, any previously generated `migrations/` dir will remain in the generated code -> it will not get removed!
Instead, we want it to get removed.
We should do it the same way we did this for .env file.

### PR DESCRIPTION
**Pull request by shayneczyzewski**
# Description

Right now, if you delete the `migrations` dir from the Wasp project root dir and run `wasp start` or `wasp build`, any previously generated `migrations` dir will remain in the generated code -> it will not get removed! Instead, we want it to get removed.

Fixes #211

## Type of change

Please select the option(s) that is more relevant.

- [ ] Code cleanup
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

File: waspc/src/Wasp/Generator/DbGenerator.hs [hunk 1]
```diff
@@ -43,13 +49,28 @@ dbSchemaFileInDbRootDir = SP.castRel dbSchemaFileInDbTemplatesDir
...
+dbMigrationsDirInDbRootDir = [reldir|migrations|]
+
 -- * Db generator
 
 genDb :: Wasp -> CompileOptions -> [FileDraft]
 genDb wasp _ =
   [ genPrismaSchema wasp
   ]
 
+preCleanup :: Wasp -> Path' Abs (Dir ProjectRootDir) -> CompileOptions -> IO ()
```
Comment (Martinsos) [inline waspc/src/Wasp/Generator/DbGenerator.hs:62]: This is looking good! Maybe you could create additional function called deleteGeneratedMigrationsDirIfRedundant and then call it in preCleanup as the only line in it, just to be a bit more verbose about clean up potentially doing more things and this being just one, clearly delineated action, but otherwise it all looks great.

There is one thing about naming that I would just like to emphasize but it has nothing to do with you right now -> it is the fact that we have this `waspMigrationsDir` vs `projectMigrationsDir`, where we use prefix `wasp` to indicate it is from the source directory with wasp code, while we use `project` to indicate it is from the generated project. Looking back at it I found it is a very confusing naming - "project" is too general, and "wasp" is also pretty lacking in information. It would probably be better if we used `srcMigrationsDir` and `genMigrationsDir`, and if we propagated this naming the whole codebase. Maybe this is ok place to start? Not sure hm. For exapmle `ProjectRootDir` -> that should probably be named `GenRootDir` or `GenProjectRootDir` or smth like that. Ok I digressed a bit :D. The only thing we might want to do here is use `src` and `gen` on new code, but I am not sure what is better - to start using new naming now and then have two different namings which we willl resolve bit by bit with time, or to stick to old naming until one day we do bigger renaming through the whole codebase. What do you think about the names btw?

File: waspc/src/Wasp/Lib.hs [hunk 2]
```diff
@@ -71,3 +73,9 @@ findDotEnvFile waspDir = do
   let dotEnvAbsPath = waspDir SP.</> [relfile|.env|]
   dotEnvExists <- doesFileExist (SP.toFilePath dotEnvAbsPath)
   return $ if dotEnvExists then Just dotEnvAbsPath else Nothing
+
+findMigrationsDir :: Path' Abs (Dir WaspProjectDir) -> IO (Maybe (Path' Abs Dir'))
+findMigrationsDir waspDir = do
+  let migrationsAbsPath = waspDir SP.</> [reldir|migrations|]
```
Comment (Martinsos) [inline waspc/src/Wasp/Lib.hs:79]: Regarding path of migrations in the wasp (source) project -> do we have a central place where it is defined? Because here you are defining it yourself, you are saying it is in waspDir, /migrations. But, what I know for certain is that CLI right now is doing copying of migrations from generator up to the src directory (yes, the opposite direction of usual, that is a bit special situation that we have, that is also interesting to observe / think about), which means it also somehow "knows" where to write them. This means this piece of knowledge is now in two places -> so we should look how to make it so it has just one source of truth.

**Review by Martinsos — COMMENTED** [review]
@shayneczyzewski did a quick pass through and it looks good, left a couple of small comments!

File: waspc/src/Wasp/Generator/DbGenerator.hs (hunk 1 above)
Comment (shayneczyzewski) [reply waspc/src/Wasp/Generator/DbGenerator.hs:62]: Good idea on the additional function to allow for more one-line cleanup items, will do!

And yes, totally agree on the naming. I originally had it called something like `src*` and `out*` but changed to match naming in this file. I was having a hard time following the naming convention myself across files/contexts, so I am glad you made that note. I think `src` and `gen` does convey more than `wasp` and `project`, so I am 💯  on board with those. I can update at least this file as the first step in that direction! 👍🏻

File: waspc/src/Wasp/Lib.hs (hunk 2 above)
Comment (shayneczyzewski) [reply waspc/src/Wasp/Lib.hs:79]: Good idea on defining a single source of truth for the migration path to be used in both places. I can try to find a good place to put it under `src` that we can also leverage in `cli`. 👍🏻

File: waspc/src/Wasp/Generator/DbGenerator.hs (hunk 1 above)
Comment (Martinsos) [reply waspc/src/Wasp/Generator/DbGenerator.hs:62]: Great! And in the future pls mention when you have hard time with a piece of code, so we can look into how to make it better!

Before we go full-on on renaming, we should probably make sure that the naming we choose makes sense.
For example, `gen` in front, although I suggested it just in previous comment :D, is (I see that now) also often used in front of function that generate sometihng, so that might be confusing (there are those functions just above - `genDb` `genPrismaSchema`). Hmmmmm. Maybe good starting point is to observe the names of the directories -> right now it is `ProjectRootDir` for generated project and `WaspProjectDir` for input/src project. Obviusly those are not very good names, since they are not even in sync. So maybe we should try to find new names for these, and that will then lead us to figuring out the other names also, is my hunch.
Hm now I am contradicting myself but I am actually thinking we should maybe not do any renaming in this PR because we will just end up introducing another naming scheme without thinking it through properly. Maybe we should leave it ias it is right now and instead create another issue where we will figure out naming, and once we do that then from that moment on we can use the new naming? WDYT?

Comment (shayneczyzewski) [reply waspc/src/Wasp/Generator/DbGenerator.hs:62]: Sounds good on question front, thanks! At this stage, sometimes it is hard to know if my confusion is just being new to Haskell/a large project or "really worth discussing", but I will default to thinking more out loud on those things that give pause. :) 

Good thinking on creating a new issue to think this through more carefully vs rushing into a name for this PR we may decide wasn't the best in the long run. Overall, I do think having consistent terms/phrasing/conventions we like and can use in Docs + code would be amazing, and it will be good to think through more carefully before deciding! 👍🏻 

I will hold off on name changes here and create a new issue. Thanks!

Comment (Martinsos) [reply waspc/src/Wasp/Generator/DbGenerator.hs:62]: Awesome, let's do that! And yeah I assumed that was the reason you didn't mention this, but exactly as you said, feel free to be more vocal it can't hurt.

Comment (shayneczyzewski) [reply waspc/src/Wasp/Generator/DbGenerator.hs:63]: Created the new issue here: https://github.com/wasp-lang/wasp/issues/396 Thanks!

File: waspc/src/Wasp/Lib.hs (hunk 2 above)
Comment (shayneczyzewski) [reply waspc/src/Wasp/Lib.hs]: I added a new commit that has a single source of truth for each of the migrations dir in the (a) wasp dir and (b) output dir: https://github.com/wasp-lang/wasp/pull/383/commits/134d19debd07f04d56c2c731486706a2b25e96d0 It feels nice now to only have two instances of `[reldir|migrations|]` in the codebase. :D

One thing you will notice is when `src` and `target` became `PathAbsDir`. This was so the expression had the same types for the `if` and `else`. I think it used to work in the old code because the way they defined the relative migration path in the first line.

However, once you make them relative to different directories in `SP` they became different types and I got the following error:
```
Migrate.hs
/Users/shayne/dev/wasp/waspc/cli/Wasp/Cli/Command/Db/Migrate.hs:93:16: error:
    • Couldn't match type ‘Wasp.Generator.DbGenerator.DbMigrationsDir’
                     with ‘()’
      Expected type: StrongPath.Internal.Path
                       StrongPath.Internal.System Abs StrongPath.Internal.Dir'
        Actual type: StrongPath.Internal.Path
                       StrongPath.Internal.System
                       Abs
                       (Dir Wasp.Generator.DbGenerator.DbMigrationsDir)
    • In the expression: dbMigrationsDirInGenProjectDirAbs
      In the expression:
        if copyDirection == CopyMigDirUp then
            dbMigrationsDirInWaspProjectDirAbs
        else
            dbMigrationsDirInGenProjectDirAbs
      In an equation for ‘target’:
          target
            = if copyDirection == CopyMigDirUp then
                  dbMigrationsDirInWaspProjectDirAbs
              else
                  dbMigrationsDirInGenProjectDirAbs
   |
93 |           else dbMigrationsDirInGenProjectDirAbs
   |    
```

Probably some way to clean it up beyond my current Haskell knowledge. I tried using a type param for `(Dir d)`and defining the type explicitly, but I could not use that in a `let`, nor make it work in other contexts. Happy to explore any ideas you may have to improve that area though since it does not feel DRY. Thanks!

File: waspc/src/Wasp/Common.hs [hunk 3]
```diff
@@ -1,6 +1,12 @@
...
   ( WaspProjectDir,
+    dbMigrationsDirInWaspProjectDir,
   )
 where
 
+import StrongPath (Dir', Path', Rel, reldir)
+
 data WaspProjectDir -- Root dir of Wasp project, containing source files.
+
+dbMigrationsDirInWaspProjectDir :: Path' (Rel WaspProjectDir) Dir'
```
Comment (Martinsos) [inline waspc/src/Wasp/Common.hs:11]: NIce, this looks like a good place for this path!

Just to double check, since I see no other paths here besides WaspProjectDir -> where are the other paths? Specifically, I know of `ext` and `.env` -> so first is external files and second is dotenv. Could you just double check where they are being defined? Maybe search project for "ext/" or "ext" or ".env". It might be that they are defined somewhere locally and were never extracted into Common because we never needed them in multiple places in which case that is fine, but I am just double checking in case they are all defined maybe somewhere at the same place and we don't know about it.

Comment (Martinsos) [reply waspc/src/Wasp/Common.hs:11]: Oh, regarding `Dir'` -> so you have a choice here, you can keep it as `Dir'` or you can make it `(Dir DbMigrationsDir)` where you would additionally define `data DbMigrationsDir` also in this file, in order to **name** the directory.

What does it mean to name it, why would you do it? Well, at ensures at type level that you are dealing with exactly this directory. For example, if there is a function that copies contents of db migrations dir from wasp source into generated project, you could say that it takes two arguments: `Path' (Rel WaspProjectDir) (Dir Wasp.Common.DbMigrationsDir)` and the second one `Path' (Rel ProjectRootDir) (Dir Wasp.Generator.Common.DbMigrationsDir)` and this way you ensure they get exactly these, correct paths, and no other path. Btw I might have missed some modules or smth here but I think you will get the idea. So in this case I would actually do that, name it, since we know there is exactly one such directory. While for example if you were reading a bunch of files/dir from somewhere, then you would use `File'` or `Dir'` for them since you don't really distinguish them in any way.

File: waspc/src/Wasp/Generator/DbGenerator.hs [hunk 4]
```diff
@@ -43,13 +50,32 @@ dbSchemaFileInDbRootDir = SP.castRel dbSchemaFileInDbTemplatesDir
 dbSchemaFileInProjectRootDir :: Path' (Rel ProjectRootDir) File'
 dbSchemaFileInProjectRootDir = dbRootDirInProjectRootDir </> dbSchemaFileInDbRootDir
 
+dbMigrationsDirInDbRootDir :: Path' (Rel DbRootDir) (Dir DbMigrationsDir)
```
Comment (Martinsos) [inline waspc/src/Wasp/Generator/DbGenerator.hs:53]: Aha, so you see, you named the DbMigrationsDir in the generated code here. So referring to my previous comment, it would make sense to also name it in the frontend of the compiler.

File: waspc/cli/Wasp/Cli/Command/Db/Migrate.hs [hunk 5]
```diff
@@ -74,30 +74,28 @@ copyDbMigrationsDir ::
...
+          then SP.Path.toPathAbsDir dbMigrationsDirInGenProjectDirAbsPath
+          else SP.Path.toPathAbsDir dbMigrationsDirInWaspProjectDirAbsPath
 
-  let target =
+  let targetPathAbsDir =
         if copyDirection == CopyMigDirUp
-          then dbMigrationsDirInWaspProjectDirAbs
-          else dbMigrationsDirInGenProjectDirAbs
+          then SP.Path.toPathAbsDir dbMigrationsDirInWaspProjectDirAbsPath
+          else SP.Path.toPathAbsDir dbMigrationsDirInGenProjectDirAbsPath
```
Comment (Martinsos) [inline waspc/cli/Wasp/Cli/Command/Db/Migrate.hs:93]: Ok, I see here what you mean by types not matching!

Yes, that is correct, this would be a problem because you are returning two different types. The question is, why would we do that, and should we rephrase what we want to do?
The thing is that here we actually don't know what source, or target, will exactly be -> they can be one folder in one case, or another folder in another case. And therefore it makes sense that type system complains. So it is us who need to make up our minds. And I think you did right, you said you know what, I actually don't care which folder it is. Ok, you went a step further and said I don't care about anything I will just turn it into FilePath and that is it :D, but that works perfectly here since this code is very localized and we need to convert it into FilePath any way just a few lines below, so I think this is perfect here. But, if you instead need to do some more complex stuff with `srcPathAbsDir` and `targetPathAbsDir` and instead wanted to have type system there to help you ensure they are absolute paths to a directory and using the filesystem conventions of underlying OS, maybe beause you are passing these to another function which takes strong path and expects such paths, then you could do that via `castDir` function (https://hackage.haskell.org/package/strong-path-1.1.1.0/docs/StrongPath.html#g:25), which casts directory to whatever you want, basically allowing you to "rename" the directory. In this case you would probalby want to rename both of these dirs to `Dir'` which effectively says they are both "any dir" and assuming that some other function that you need to pass these to takes `Dir'`, you would be good to go.

But, as I said, what you did here is actually perfect taking into account the circumstances, I wrote other stuff above just so you get an idea for some other use cases where it might be useful.

**Review by Martinsos — COMMENTED** [review]
Nice, I believe this is mostly it then? Left some more comments! You can probably pull it out of "draft" stage now?

File: waspc/src/Wasp/Common.hs (hunk 3 above)
Comment (shayneczyzewski) [reply waspc/src/Wasp/Common.hs:11]: I will double check on where other paths are defined to make sure it wasn't somewhere else vs not yet extracted into Common! 👍🏻 

Good call on making it explicitly `(Dir DbMigrationsDir)` to help avoid any issues of mixing the final dir type, I will make that change.

File: waspc/src/Wasp/Generator/DbGenerator.hs (hunk 4 above)
Comment (shayneczyzewski) [reply waspc/src/Wasp/Generator/DbGenerator.hs:53]: Will do!

File: waspc/cli/Wasp/Cli/Command/Db/Migrate.hs (hunk 5 above)
Comment (shayneczyzewski) [reply waspc/cli/Wasp/Cli/Command/Db/Migrate.hs:93]: Appreciate the explanation! Thanks for confirming the approach, and the pointer on `castDir` which will likely become super helpful in future! 👍🏻

File: waspc/src/Wasp/Common.hs (hunk 3 above)
Comment (shayneczyzewski) [reply waspc/src/Wasp/Common.hs]: The change from `Dir'` to `Dir DbMigrationsDir` can be found here: https://github.com/wasp-lang/wasp/pull/383/commits/3aa6b67e3c9f075487746d7e153de7ede4f54846 👍🏻 

In regard to other places where we have external paths defined, in `cli` most are in cli/Wasp/Cli/Common.hs. On the `src` side, the convention appears to be more using the *Generator.hs files or their corresponding /Generator/*Generator/Common.hs files and keeping the definitions pretty localized to their usage. So for this PR, I do not think we missed putting the topmost declarations into a more appropriate place than  and it feels like it is following the conventions.

In the future, we can consider a couple things:
- Define more common paths in src/Wasp/Common.hs we can leverage in both `cli` and `src` (also helpful as Generators do more Wasp dir work)
- Cleaning up .env by defining it in src/Wasp/Common.hs and corresponding usage in src/Wasp/Lib.hs. All other `Path' Abs (Dir WaspProjectDir)` usage is in `cli` right now.

**Comment by shayneczyzewski** [comment]
I believe I have addressed all open feedback @Martinsos and it is ready for a final review. Thanks so much! 👍🏻

File: waspc/src/Wasp/Common.hs (hunk 3 above)
Comment (Martinsos) [reply waspc/src/Wasp/Common.hs]: Ok, that all sounds good, including tasks for the future!

**Review by Martinsos — APPROVED** [review]
Great @shayneczyzewski , this is looking good to me :)!! I think we covered everything and solution is nice -> let's merge!

**Comment by shayneczyzewski** [comment]
Thanks again @Martinsos for all the great feedback and context. Merging momentarily. 🚀
