### PR TITLE
Propagates error exit code for `wasp deploy`

### LINKED ISSUE #1163: `wasp deploy` should propagate exit status code from TS project
**Describe the bug**
Currently, `wasp deploy` does not propagate the exit status code from the TS project.

**Expected behavior**
It should. :) This will enable use in CI and other scripted contexts.

### PR DESCRIPTION
**Pull request by shayneczyzewski**
### Description

Now that the Wasp CLI forwards error exit codes, I updated `wasp deploy` to make use of it. This will help users who want to deploy in CI, for example.

Fixes #1163 

### Select what type of change this PR introduces:

1. [ ] **Just code/docs improvement** (no functional change). 
2. [x] **Bug fix** (non-breaking change which fixes an issue).
3. [ ] **New feature** (non-breaking change which adds functionality).
4. [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected).

### Update Waspc ChangeLog and version if needed
If you did a bug fix, new feature, or breaking change, that affects waspc, make sure you satisfy the following:
1. [x] I updated [ChangeLog.md](https://github.com/wasp-lang/wasp/blob/main/waspc/ChangeLog.md) with description of the change this PR introduces.
2. [ ] I bumped waspc version in [waspc.cabal](https://github.com/wasp-lang/wasp/blob/main/waspc/waspc.cabal) to reflect changes I introduced, with regards to the version of the latest wasp release, if the bump was needed.

### CODE REVIEW

File: waspc/cli/src/Wasp/Cli/Command/Deploy.hs [hunk 1]
```diff
@@ -3,19 +3,23 @@ module Wasp.Cli.Command.Deploy
...
+  deployResult <- liftIO $ do
     -- `getExecutablePath` has some caveats:
     --   https://frasertweedale.github.io/blog-fp/posts/2022-05-10-improved-executable-path-queries.html
     -- Once we upgrade to GHC 9.4 we should change to `executablePath`, but this should be ok for
     -- our purposes.
     waspExePath <- getExecutablePath
     Wasp.Project.Deployment.deploy waspExePath waspProjectDir cmdArgs
+  case deployResult of
+    Left err -> throwError $ CommandError "Deploy command failed" err
+    Right () -> return ()
```
Comment (infomiho) [inline waspc/cli/src/Wasp/Cli/Command/Deploy.hs:25]:
```suggestion
  either (throwError . CommandError "Deploy command failed") return deployResult
```

Channeling my inner Martin

**Comment by infomiho** [comment]
Seems to work fine on my machine.

Screenshot 2023-05-02 at 17 01 44

**Review by infomiho — APPROVED** [review]

File: waspc/cli/src/Wasp/Cli/Command/Deploy.hs (hunk 1 above)
Comment (shayneczyzewski) [reply waspc/cli/src/Wasp/Cli/Command/Deploy.hs:25]: Haha love it, and this looks much better thnx!

File: waspc/src/Wasp/Project/Deployment.hs [hunk 2]
```diff
@@ -27,18 +28,22 @@ loadUserDockerfileContents waspDir = do
...
   runCommandAndPrintOutput $ runNodeCommandAsJob deployDir "node" deployScriptArgs J.Server
   where
+    runCommandAndPrintOutput :: J.Job -> IO (Either String ())
     runCommandAndPrintOutput job = do
       chan <- newChan
-      void $ concurrently (printJobMsgsUntilExitReceived chan) (job chan)
+      (_, exitCode) <- concurrently (printJobMsgsUntilExitReceived chan) (job chan)
+      case exitCode of
+        ExitSuccess -> return $ Right ()
+        ExitFailure code -> return $ Left $ "Deploy command failed with exit code: " ++ show code
```
[the remark this answers is not in the document]
Comment (shayneczyzewski) [reply waspc/src/Wasp/Project/Deployment.hs:49]: Haha, I am on the fence on this one, only because the existing way is pretty common in the code base. So I may stick with that as is, but I like the thinking here :D Thanks!
