### PR TITLE
Fix incorrect parsing of escaped strings in Wasp

### LINKED ISSUE #693: Parser does not correctly handle escaped quotes inside strings
**Describe the bug**
If you have a .wasp file with escaped quotes inside a string, like this:

```css
app todoApp {
  title: "ToDo App",
  head: [
    "<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap\" />"
  ],
  ...
```

when you `wasp compile`, the resulting HTML file will still have those escape characters, like this:

```html
...

  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap\" />
  
  <title>ToDo App</title>
...
```

**Expected behavior**
They should be un-escaped properly during generation, and instead result in an HTML file like this:

```html
...

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap" />
  
  <title>ToDo App</title>
...
```

### PR DESCRIPTION
**Pull request by Martinsos**
Actual fix is just two lines, you can see that done in the very first commit.
I actually added two more commits where I did a bit of refactoring:
1. Refactored golden tests for Parser just a bit.
2. Moved PrettyPrinting of Parser AST to nicer place.

Fixes #693

### CODE REVIEW

File: waspc/src/Wasp/Analyzer/Parser/AbstractParser.hs [hunk 1]
```diff
@@ -91,7 +91,7 @@ coerceExpr (SyntaxNode kind width children : remaining)
   | otherwise = do
       startPos <- gets pstateStartPos
       expr <- case kind of
-        S.String -> AST.StringLiteral . tail . init <$> consume width
+        S.String -> AST.StringLiteral . read <$> consume width
```
Comment (Martinsos) [inline waspc/src/Wasp/Analyzer/Parser/AbstractParser.hs:94]: This is the actual fix! Instead of stripping first and last quote, we properly parse it with `read`.

Comment (Martinsos) [reply waspc/src/Wasp/Analyzer/Parser/AbstractParser.hs:94]: @craigmc08 just to check, did I miss something here? Was there maybe a reason why before you used `tail . init` and not `read`? Because now with `read`, it correctly parses string when it has escaped characters in it, while with `tail . init` it didn't.

File: waspc/test/Analyzer/ParserTest/parseStatementsTests/declsDictsAndLiterals.golden [hunk 2]
```diff
@@ -5,7 +5,7 @@
         (String@2:11-25 value="Hello Wasp =}")
       )
       (DictEntry key=escapedString
-        (String@3:18-29 value="Look, a \\\"")
+        (String@3:18-29 value="Look, a \"")
```
Comment (Martinsos) [inline waspc/test/Analyzer/ParserTest/parseStatementsTests/declsDictsAndLiterals.golden:8]: This is what it works like now, which is correct behaviour.

**Review by shayneczyzewski — APPROVED** [review]
Looks good to me, @Martinsos! Nice job on the first PR for the new parser. 🥳  Verified the build output now minimizes again too. 👍🏻

File: waspc/src/Wasp/Analyzer/Parser/AbstractParser.hs (hunk 1 above)
Comment (craigmc08) [reply waspc/src/Wasp/Analyzer/Parser/AbstractParser.hs:94]: This was a mistake (probably because I didn't write the golden file for the test case correctly). It should be `read`.

File: waspc/src/Wasp/Analyzer/Parser/PrettyPrinter.hs [hunk 3]
```diff
@@ -0,0 +1,16 @@
+module Wasp.Analyzer.Parser.PrettyPrinter
+  ( prettyPrintParserResult,
+  )
+where
+
+import Wasp.Analyzer.Parser hiding (withCtx)
```
Comment (sodic) [inline waspc/src/Wasp/Analyzer/Parser/PrettyPrinter.hs:6]: Why are we hiding `withCtx`?
Also, we should probably be doing a qualified import.

Finally, the best choice is probably `import Wasp.Analyzer.Parser (ParseError, AST)`

File: waspc/src/Wasp/Analyzer/Parser/PrettyPrinter.hs [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+import Wasp.Analyzer.Parser.AST.PrettyPrinter (prettyPrintAST, prettyPrintCtx)
+import Wasp.Analyzer.Parser.ParseError (getErrorMessageAndCtx)
+import Wasp.Util (indent)
+
+prettyPrintParserResult :: Either ParseError AST -> String
+prettyPrintParserResult (Left err) =
+  let (message, ctx) = getErrorMessageAndCtx err
+      locationStr = "at " ++ prettyPrintCtx ctx
+   in "Parse error " ++ locationStr ++ ":\n" ++ indent 2 message ++ "\n"
+prettyPrintParserResult (Right ast) = prettyPrintAST ast
```
Comment (sodic) [inline waspc/src/Wasp/Analyzer/Parser/PrettyPrinter.hs:16]: Hm, does it make sense to flip the pattern match (i.e., put the `Right` case first because it's a one liner). I realize it also makes sense to do `Left` and then `Right` because it's natural to go from left to right. Not sure which one is more idiomatic, I'll leave that to you.

Another (possibly subjective) remark, I think using a `where` block makes this a bit easier to understand (I also moved the `"at"`):
```haskell
prettyPrintParserResult (Left err) = "Parse error at" ++ locationStr ++ ":\n" ++ indent 2 message ++ "\n"
  where
    (message, ctx) = getErrorMessageAndCtx err
    locationStr = prettyPrintCtx ctx
```
And one last thing I'm never sure of: Is it appropriate to make this function responsible for the trailing newline, or is that something we should leave to the caller?

**Review by sodic — COMMENTED** [review]
Looks good, left a couple of minor remarks :)

File: waspc/src/Wasp/Analyzer/Parser/AST/PrettyPrinter.hs [hunk 5]
```diff
@@ -0,0 +1,64 @@
...
+    showLiteral value = " value=" ++ show value
+
+prettyPrintWithCtx :: String -> Ctx -> String
+prettyPrintWithCtx name ctx = name ++ "@" ++ prettyPrintCtx ctx
+
+prettyPrintCtx :: Ctx -> String
+prettyPrintCtx (Ctx (SourceRegion (SourcePosition sl sc) (SourcePosition el ec)))
+  | sl == el && sc == ec = show sl ++ ":" ++ show sc
+  | sl == el = show sl ++ ":" ++ show sc ++ "-" ++ show ec
+  | otherwise = show sl ++ ":" ++ show sc ++ "-" ++ show el ++ ":" ++ show ec
```
[the remark this answers is not in the document]
Comment (Martinsos) [reply waspc/src/Wasp/Analyzer/Parser/AST/PrettyPrinter.hs:64]: Certainly, I will do it, it will be more readable!

File: waspc/src/Wasp/Analyzer/Parser/PrettyPrinter.hs (hunk 4 above)
Comment (Martinsos) [reply waspc/src/Wasp/Analyzer/Parser/PrettyPrinter.hs:16]: Love the suggestion!
I think it makes sense to handle Right first since it is shoter + it is a positive / normal use case, while Left is an "error" use case, which I would prefer reading after I read the core logic.
I also added that where clause, it does make it easier to read this.
As for newline -> ha that is a tricky question, it really comes down to how we establish a convention with ourselves. I would actually vote for not having it here, so that caller can choose if they want it or not. I moved it out.

Comment (sodic) [reply waspc/src/Wasp/Analyzer/Parser/PrettyPrinter.hs:16]: Oh, and if you remove the newline, you may find it more readable to construct the final string using `unlines`.

Comment (Martinsos) [reply waspc/src/Wasp/Analyzer/Parser/PrettyPrinter.hs:16]: Correction: I haven't moved it out at the end as the whole pretty parser logic is providing newlines in this fashion, embedded into the thing it prints, even for lower level stuff like statements, expressions and similar, so I would have to refactor the whole thing to use this different approach of caller supplying newlines, which I think would be too much work at the moment compared to what we get for it.

**Comment by Martinsos** [comment]
@sodic I responded to all comments!

File: waspc/src/Wasp/Analyzer/Parser/PrettyPrinter.hs (hunk 4 above)
Comment (sodic) [reply waspc/src/Wasp/Analyzer/Parser/PrettyPrinter.hs]: I like it like this, but I have a feeling you'd prefer to change the order of variables in the where clause :D

**Review by sodic — APPROVED** [review]
All good
