### PR TITLE
Make warnings filterable to avoid redundant messages

### LINKED ISSUE #597: extra warning in the db migration process
**Describe the bug**
I'm following the todo app, in ["Task Entity section"](https://wasp-lang.dev/docs/tutorials/todo-app/task-entity), I ran the following command for the first time,  but it shows me a warning to run it again. 

```bash
wasp db migrate-dev
```

**To Reproduce**
Follow todo instructions, step by step till Task Entity

**Expected behavior**
Not showing the warning of the command for the same command.

**Screenshots**
Screen Shot 2022-05-19 at 2 07 20 PM

### PR DESCRIPTION
**Pull request by shayneczyzewski**
# Description

This change allows you to send a filter function as part of the compile options, so you can optionally exclude certain warnings depending on the CLI command being executed. This is helpful with `db migrate-dev`, for example.

The reason this is needed is we do our error/warning checks during compilation, and we compile before we run every command. So if you have not yet migrated, it will warn you during compilation that you need to migrate, even if you are running `db migrate-dev`. In that case we should filter out that warning since it is redundant.

To address the ability to filter, I added a new `GeneratorWarning`. Additionally, I chose _not_ to change the `String` error/warning interface between `Lib.compile` and the CLI world, as that would be a pretty big change and I'm unsure of the benefit of including the warning types past that layer.

Fixes #597 

## Type of change

Please select the option(s) that is more relevant.

- [ ] Code cleanup
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

File: waspc/cli/src/Wasp/Cli/Command/Build.hs [hunk 1]
```diff
@@ -56,5 +59,12 @@ buildIO waspProjectDir buildDir = compileIOWithOptions options waspProjectDir bu
...
           isBuild = True,
-          sendMessage = cliSendMessage
+          sendMessage = cliSendMessage,
+          -- Ignore "DB needs migration warnings" during build, as that is not a required step.
+          warningsFilter =
+            filter
+              ( \case
+                  GeneratorNeedsMigrationWarning _ -> False
+                  _ -> True
+              )
```
Comment (shayneczyzewski) [inline waspc/cli/src/Wasp/Cli/Command/Build.hs:69]: Any cleaner way to do this? If I _only_ wanted `GeneratorNeedsMigrationWarning` I could use List comprehensions (a la `[x | Just x <- xs]`), but unsure of a similar way of doing that if I want everything _except_ a particular Data Constructor.

File: waspc/src/Wasp/CompileOptions.hs [hunk 2]
```diff
@@ -16,5 +17,6 @@ data CompileOptions = CompileOptions
     -- We give the compiler the ability to send messages. The code that
     -- invokes the compiler (such as the CLI) can then implement a way
     -- to display these messages.
-    sendMessage :: SendMessage
+    sendMessage :: SendMessage,
+    warningsFilter :: [GeneratorWarning] -> [GeneratorWarning]
```
Comment (Martinsos) [inline waspc/src/Wasp/CompileOptions.hs:21]: This is where this field is defined, so this is also where we should provide rich comment explaining its purpose and intention.

**Review by Martinsos — APPROVED** [review]
At first my instinct was to apply this filter to output of Lib.hs, but I forgot it returns Strings and loses detailed information about the error.
I think in the future we will want to have it work different, to have Lib.hs provide more details on the errors it returns. But for now, this is probably the best way, as you did.
I left some minor comments but in general it looks good!

File: waspc/cli/src/Wasp/Cli/Command/Build.hs (hunk 1 above)
Comment (shayneczyzewski) [reply waspc/cli/src/Wasp/Cli/Command/Build.hs:69]: Ok, thanks for the sanity check, I appreciate it.

File: waspc/cli/src/Wasp/Cli/Command/Compile.hs [hunk 3]
```diff
@@ -24,13 +25,18 @@ import qualified Wasp.Message as Msg
 
 compile :: Command ()
 compile = do
+  waspProjectDir <- findWaspProjectRootDirFromCwd
```
[the remark this answers is not in the document]
Comment (shayneczyzewski) [reply waspc/cli/src/Wasp/Cli/Command/Compile.hs:28]: Yeah, it is not ideal, but I'm not too sure of a clean way to avoid it twice. I see a few options:
- Try to pull it out of `externalCodeDirPath` but that is just duplication in the opposite direction :D
- Add a new field to `CompileOptions` just for `waspProjectDir`, and then just add helpers for `externalCodeDirPath` and maybe even the generated out dir path (or whatever else others need)
- Pass it into `compileWithOptions`, but now that puts a new burden on all callers, which is prob worse

Option 2 seems likely the best, but I wonder if we should tackle that refactor right now? My inclination is probably to pay the redundancy price in this PR. Can TODO it so we do not forget option 2 though.

File: waspc/src/Wasp/CompileOptions.hs (hunk 2 above)
Comment (shayneczyzewski) [reply waspc/src/Wasp/CompileOptions.hs:21]: Sounds good! I can add a comment and can update the name 👍🏻 Thanks!

**Comment by shayneczyzewski** [comment]
> At first my instinct was to apply this filter to output of Lib.hs, but I forgot it returns Strings and loses detailed information about the error. I think in the future we will want to have it work different, to have Lib.hs provide more details on the errors it returns. But for now, this is probably the best way, as you did. I left some minor comments but in general it looks good!

Thanks again for the review @Martinsos. Agree that we will want to eventually change that interface from Lib to CLI to be better typed and not `String`, but that may be a decent refactor given we return non-`GeneratorWarning`s/`GeneratorError`s at this time as well. That was the main reason I figured we should address later. But once we do it will be a small change for this filter idea to make use of.

Also, there was a question around the redundancy of getting the Wasp project root dir. I had one idea, but wasn't sure we do want to change compile options for it, so used a TODO for now so we can merge this to address the user bug. If you do like that idea I can followup after this and try it out. Thanks!
