### PR TITLE
Fix realworld Wasp example app

### LINKED ISSUE #197: Deleting an article does not work in real world example

### PR DESCRIPTION
**Pull request by sodic**
Fixes several issues and warnings in the _realworld_ example app (mainly [the one @shayneczyzewski noticed](https://github.com/wasp-lang/wasp/pull/554#issuecomment-1095268143)).

Also fixes #197

### CODE REVIEW

File: examples/realworld/ext/MainPage.js [hunk 1]
```diff
@@ -1,5 +1,4 @@
 import React, { useState } from 'react'
-import { Link } from 'react-router-dom'
```
Comment (sodic) [inline examples/realworld/ext/MainPage.js:2]: I removed all the unused imports/variables to prevent console warnings.

File: examples/realworld/ext/article/components/ArticleEditorPage.js [hunk 2]
```diff
@@ -44,7 +43,7 @@ const ArticleEditorPage = (props) => {
   //   When is article null, when not, should I look into combination of article and articleSlug, then
   //   there is this 'enabled' which I need on the other hand -> uff. And what if I get error? humpf!
   const articleSlug = props.match.params.articleSlug
-  const { data: article, error: articleError } = useQuery(getArticle, { slug: articleSlug }, { enabled: articleSlug })
+  const { data: article, error: articleError } = useQuery(getArticle, { slug: articleSlug }, { enabled: !!articleSlug })
```
Comment (sodic) [inline examples/realworld/ext/article/components/ArticleEditorPage.js:46]: This fixes [the 500 error @shayneczyzewski noticed](https://github.com/wasp-lang/wasp/pull/554#issuecomment-1095268143).

File: examples/realworld/ext/article/components/ArticleViewPage.js [hunk 3]
```diff
@@ -105,11 +105,7 @@ const ArticleViewPage = (props) => {
         </Grid>
 
         <Grid item xs={8}>
-          <p>
-            <Typography variant="h5">
-              <ReactMarkdown children={article.markdownContent} />
-            </Typography>
-          </p>
+            <ReactMarkdown children={article.markdownContent} />
```
Comment (sodic) [inline examples/realworld/ext/article/components/ArticleViewPage.js:108]: Removing the parents fixed most of the _invalid HTML errors_ without affecting the app's appearance all that much.

File: examples/realworld/main.wasp [hunk 4]
```diff
@@ -104,7 +104,7 @@ entity Comment {=psl
 
     user            User     @relation(fields: [userId], references: [id])
     userId          Int
-    article         Article  @relation(fields: [articleId], references: [id])
+    article         Article  @relation(fields: [articleId], references: [id], onDelete: Cascade)
```
Comment (sodic) [inline examples/realworld/main.wasp:107]: This fixes #197

File: examples/realworld/ext/article/components/ArticleEditorPage.js (hunk 2 above)
Comment (Martinsos) [reply examples/realworld/ext/article/components/ArticleEditorPage.js:46]: Uff nice catch!

File: examples/realworld/ext/article/components/ArticleViewPage.js [hunk 5]
```diff
@@ -84,6 +83,7 @@ const ArticleViewPage = (props) => {
     if (!window.confirm('Are you sure you want to delete the article?')) return
     try {
       await deleteArticle({ id: article.id })
+      history.push('/')
```
Comment (Martinsos) [inline examples/realworld/ext/article/components/ArticleViewPage.js:86]: Why did we give up on this? It happens automatically?

File: examples/realworld/ext/article/components/ArticleViewPage.js (hunk 3 above)
Comment (Martinsos) [reply examples/realworld/ext/article/components/ArticleViewPage.js:108]: Ah yes, it is me who for some reason keeps thinking that I can put anything in `p`!

File: examples/realworld/ext/article/queries.js [hunk 6]
```diff
@@ -84,6 +84,9 @@ export const getArticle = async ({ slug }, context) => {
     where: { slug },
     include: articleInclude
   })
+  if (!article) { 
+      throw new HttpError(404)
```
Comment (Martinsos) [inline examples/realworld/ext/article/queries.js:88]: Nice! Do notice though that indentation everywhere is 2 while here it is 4 :P.

File: examples/realworld/main.wasp (hunk 4 above)
Comment (Martinsos) [reply examples/realworld/main.wasp:107]: Awesome!

**Review by Martinsos — APPROVED** [review]
Nice! Thorough as always!

File: examples/realworld/ext/article/components/ArticleEditorPage.js (hunk 2 above)
Comment (shayneczyzewski) [reply examples/realworld/ext/article/components/ArticleEditorPage.js:46]: Awesome find and fix, thanks! 👏🏻

File: examples/realworld/ext/article/components/ArticleViewPage.js (hunk 5 above)
Comment (sodic) [reply examples/realworld/ext/article/components/ArticleViewPage.js:86]: We didn't give up (the PR adds this line). I added it in precisely because it doesn't happen automatically :smile:

File: examples/realworld/ext/article/queries.js (hunk 6 above)
Comment (sodic) [reply examples/realworld/ext/article/queries.js:88]: I'll blame this on the editor. I'll fix it.

**Comment by sodic** [comment]
@Martinsos Hm, I should also include the database migration to the PR, right?
