### PR TITLE
[Analyzer] Reverse the order of Wasp error messages

### LINKED ISSUE #414: [Analyzer] Reverse the order in which Analyzer error message is described
Right now, Analyzer (compiler) error messages are shown like this:
```
Type error:
  For dictionary field 'dependencies':
    For list element:
      For dictionary field 'version':
        Expected type: string
        Actual type:   number
```

So first we describe the type of the error (`Type Error`), then we describe its context (in dictionary field X, in list, in ...), and then we describe the actual error (`Expected ... Actual ...`).

The thing is however, that this is probably not the optimal way to show error, since we are first starting with less important information and end with the most important information.
We should probably inverse the order, and do smth like:

```
Type error:
  Unexpected type: string
  Actual type:     number
  
    └> For dictionary field 'version'
      └> In list
        └> For dictionary field 'dependencies'
```

This is also how Haskell reports errors: first the error itself, then the context from the inside out.

We should probably check how errors look in couple of other popular compilers/languages, decide on exact format, and then refactor our error message construction to match it.

As for the files where the most of the changes will be happening, those will probably be:
- https://github.com/wasp-lang/wasp/blob/master/waspc/src/Wasp/Analyzer/Parser/ParseError.hs
- https://github.com/wasp-lang/wasp/blob/master/waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs
- https://github.com/wasp-lang/wasp/blob/master/waspc/src/Wasp/Analyzer/Evaluator/EvaluationError.hs

### PR DESCRIPTION
**Pull request by sodic**
# Description

This PR changes the order in which the compiler displays error messages and their context (check the issue for details).

Fixes #414

## Type of change

Please select the option(s) that is more relevant.

- [x] Code cleanup
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

File: waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs [hunk 1]
```diff
@@ -82,22 +82,35 @@ data TypeCoercionErrorReason e
     ReasonDictWrongKeyType String e
   deriving (Eq, Show)
 
-getTypeCoercionErrorMessageAndCtx :: (Type -> TypedExpr -> String) -> TypeCoercionError -> (String, Ctx)
-getTypeCoercionErrorMessageAndCtx getUncoercableTypesMsg (TypeCoercionError (WithCtx ctx texpr) t reason) =
+second :: (b -> d) -> (a, b, c) -> (a, d, c)
+second f (x, y, z) = (x, f y, z)
```
Comment (sodic) [inline waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs:86]: This should most likely be in `Wasp.Util`. Should I even be implementing it or is it a code smell (`second` from `Control.Arrow` only works on pairs).

File: waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs [hunk 2]
```diff
@@ -82,22 +82,35 @@ data TypeCoercionErrorReason e
...
-    ReasonDictExtraKey key -> ("Unexpected dictionary field '" ++ key ++ "'", ctx)
+      second (("-> In dictionary field '" ++ key ++ "'") :) $ extractTypeErrorMessagesAndCtx getUncoercableTypesMsg e
+    ReasonDictNoKey key -> ("-> Missing required dictionary field '" ++ key ++ "'", [], ctx)
+    ReasonDictExtraKey key -> ("-> Unexpected dictionary field '" ++ key ++ "'", [], ctx)
     ReasonDecl -> uncoercableTypesMsgAndCtx
     ReasonEnum -> uncoercableTypesMsgAndCtx
     ReasonUncoercable -> uncoercableTypesMsgAndCtx
   where
-    uncoercableTypesMsgAndCtx = (getUncoercableTypesMsg t texpr, ctx)
+    uncoercableTypesMsgAndCtx = (getUncoercableTypesMsg t texpr, [], ctx)
```
Comment (sodic) [inline waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs:101]: Since we give the "real" message special treatment (I.e., we display it first, in an order inconsistent with the rest of the messages), I thought that it probably shouldn't be bundled in the same array as the rest of them.

Also, I decided to put the additional messages in an array (as opposed to a string) and handle the indentation separately. I felt weird initializing the second member of the tuple with `""`. It also caused the `indent 2` part to add trailing spaces.

With that said, there is probably a better way to do most of this. Looking forward to the comments :)

File: waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs [hunk 3]
```diff
@@ -82,22 +82,35 @@ data TypeCoercionErrorReason e
     ReasonDictWrongKeyType String e
   deriving (Eq, Show)
 
-getTypeCoercionErrorMessageAndCtx :: (Type -> TypedExpr -> String) -> TypeCoercionError -> (String, Ctx)
-getTypeCoercionErrorMessageAndCtx getUncoercableTypesMsg (TypeCoercionError (WithCtx ctx texpr) t reason) =
+second :: (b -> d) -> (a, b, c) -> (a, d, c)
+second f (x, y, z) = (x, f y, z)
+
+extractTypeErrorMessagesAndCtx :: (Type -> TypedExpr -> String) -> TypeCoercionError -> (String, [String], Ctx)
```
Comment (sodic) [inline waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs:88]: Couldn't come up with a better name for this helper function. Perhaps I'll end up removing it after the comments.

File: waspc/src/Wasp/Util.hs [hunk 4]
```diff
@@ -67,12 +68,22 @@ headSafe :: [a] -> Maybe a
 headSafe [] = Nothing
 headSafe xs = Just (head xs)
 
+second :: (b -> d) -> (a, b, c) -> (a, d, c)
+second f (x, y, z) = (x, f y, z)
```
Comment (sodic) [inline waspc/src/Wasp/Util.hs:72]: `second` from `Control.Arrow` only works on pairs (and I have a tuple of 3). Is implementing something like this a code smell?

File: waspc/src/Wasp/Util.hs [hunk 5]
```diff
@@ -67,12 +68,22 @@ headSafe :: [a] -> Maybe a
...
 indent :: Int -> String -> String
-indent numSpaces = intercalate "\n" . map (replicate numSpaces ' ' ++) . splitOn "\n"
+indent numSpaces = intercalate "\n" . map (stripIfEmpty . (indentation ++)) . splitOn "\n"
+  where
+    indentation = replicate numSpaces ' '
+
+stripIfEmpty :: String -> String
+stripIfEmpty str
+  | null $ Text.unpack $ Text.strip $ Text.pack str = ""
+  | otherwise = str
```
Comment (sodic) [inline waspc/src/Wasp/Util.hs:86]: This addition prevents indenting blank lines (check _UtilTest.hs_ for details).

File: waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs [hunk 6]
```diff
@@ -82,22 +79,34 @@ data TypeCoercionErrorReason e
...
-    uncoercableTypesMsgAndCtx = (getUncoercableTypesMsg t texpr, ctx)
+    uncoercableTypesMsgAndCtx = (getUncoercableTypesMsg t texpr, [], ctx)
+
+joinAdditionalMessages :: [String] -> String
+joinAdditionalMessages [] = ""
+joinAdditionalMessages msgChain = foldr1 appendMsg msgChain
+  where
+    appendMsg curr acc = intercalate ":\n" [curr, indent 2 acc]
+
+getTypeCoercionErrorMessageAndCtx :: (Type -> TypedExpr -> String) -> TypeCoercionError -> (String, Ctx)
```
Comment (Martinsos) [inline waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs:103]: In general, the order of functions in this file is not great. Normally we try to keep them ordered top -> bottom, so that the ones above use the others below.
This is not your doing, they were already ordered wrong, by me previously.
But we could fix that now. So `getUnificationErrorMessageAndCtx` and `getWeakenErrorMessageAndCtx` would go first, then we would have `getTypeCoercionErrorMessageAndCtx`, and only then we would have `extractTypeErrorMessagesAndCtx`, so it reads like a story, first high level stuff, then the implementation details.

**Review by Martinsos — COMMENTED** [review]
@sodic nice work!
I left some comments, mostly naming / moving things a bit, but nothing major.

File: waspc/src/Wasp/Util.hs [hunk 7]
```diff
@@ -67,12 +68,22 @@ headSafe :: [a] -> Maybe a
...
 
 indent :: Int -> String -> String
-indent numSpaces = intercalate "\n" . map (replicate numSpaces ' ' ++) . splitOn "\n"
+indent numSpaces = intercalate "\n" . map (stripIfEmpty . (indentation ++)) . splitOn "\n"
+  where
+    indentation = replicate numSpaces ' '
+
+stripIfEmpty :: String -> String
+stripIfEmpty str
+  | null $ Text.unpack $ Text.strip $ Text.pack str = ""
```
Comment (Martinsos) [inline waspc/src/Wasp/Util.hs:85]: I would skip all the Text packing and unpacking, and instead do smth like
```hs
import Data.Char (isSpace)

stripIfEmpty :: String -> String
stripIfEmpty str | all isSpace str = ""
                 | otherwise = str
```

Comment (Martinsos) [reply waspc/src/Wasp/Util.hs:85]: Also, would rename it to something else, as concept of stripping if empty is weird. Also, what does empty mean? I would intuitively expect empty to be "", not string consisting of white spaces.

Maybe `toEmptyStringIfAllWhiteSpace`?

File: waspc/test/UtilTest.hs [hunk 8]
```diff
@@ -35,6 +35,11 @@ spec_toUpperFirst = do
   it "Capitalizes first letter of string" $ do
     toUpperFirst "fooBar" `shouldBe` "FooBar"
 
+spec_second :: Spec
+spec_second = do
+  it "Applies the function to the second element of a tuple of size 3." $ do
+    second negate ("1", 2, True) `shouldBe` ("1", -2, True)
```
Comment (Martinsos) [inline waspc/test/UtilTest.hs:41]: Keep an eye on these warnings! You need to specify which types are these, smth like `("1" :: String, 2 :: Int, True)`

**Review by Martinsos — COMMENTED** [review]
Couple more comments because I didn't see the changes in Util.hs while doing previous review.

File: waspc/test/UtilTest.hs (hunk 8 above)
Comment (sodic) [reply waspc/test/UtilTest.hs:41]: Thanks, I meant to ask what this was about, will do.

File: waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs [hunk 9]
```diff
@@ -82,22 +79,35 @@ data TypeCoercionErrorReason e
...
+    ReasonDictNoKey key -> ("-> Missing required dictionary field '" ++ key ++ "'", [], ctx)
+    ReasonDictExtraKey key -> ("-> Unexpected dictionary field '" ++ key ++ "'", [], ctx)
     ReasonDecl -> uncoercableTypesMsgAndCtx
     ReasonEnum -> uncoercableTypesMsgAndCtx
     ReasonUncoercable -> uncoercableTypesMsgAndCtx
   where
-    uncoercableTypesMsgAndCtx = (getUncoercableTypesMsg t texpr, ctx)
+    uncoercableTypesMsgAndCtx = (getUncoercableTypesMsg t texpr, [], ctx)
+
+joinAdditionalMessages :: [String] -> String
```
[the remark this answers is not in the document]
Comment (sodic) [reply waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs:97]: I changed the name to something similar to what you suggested.

I tried putting the function into `where`, but as it got longer (with the `prefix` thing), I ended up preferring it separately (I also didn't like the nested `where` expression).

File: waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs [hunk 10]
```diff
@@ -82,22 +79,35 @@ data TypeCoercionErrorReason e
...
+joinAdditionalMessages [] = ""
+joinAdditionalMessages msgChain = foldr1 appendMsg msgChain
```
[the remark this answers is not in the document]
Comment (sodic) [reply waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs:99]: Thanks for the doc! I'll take a look and decide.

> Since you have this function, I would also move the " -> " here, so it becomes part of "concatenation" logic, not the part of actual error message production logic.

Hm, I thought about this, but decided against it. We prefix all messages with arrows, even the first one (i.e., it's not a part of the concatenator). Still, it's nicer not having to repeat the arrow four times. I think I'll add it here.

File: waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs [hunk 11]
```diff
@@ -117,3 +97,38 @@ getWeakenErrorMessageAndCtx = getTypeCoercionErrorMessageAndCtx $
...
+      | null ctxMsgs = typesErrorMsg
+      | otherwise = intercalate "\n\n" [typesErrorMsg, concatContextualMsgs ctxMsgs]
+
+-- | Takes a function for constructing a type coercion error message, and a `TypeCoercionError`.
+--
+-- It recursively traverses the error stack and returns a tuple containing:
+-- - The original type coercion error message
+-- - An array of contextual messages further explaining the original error
+-- - The error's context
+getUncoercableTypesMsgAndCtxMsgsAndCtx :: (Type -> TypedExpr -> String) -> TypeCoercionError -> (String, [String], Ctx)
```
Comment (Martinsos) [inline waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs:115]: Since you went with a nice long name, I would add couple more words into it: `getUncoercableTypesErrorMsgAndErrorCtxMsgsAndParsingCtx`
because otherwise it is really hard to say what is Msg vs CtxMsgs vs Ctx -> it all sounds the same. But ErrorMsg vs ErrorCtxMsgs vs ParsingCtx -> well, still not great but maybe a bit better?

Ok, we have comment at least.

File: waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs [hunk 12]
```diff
@@ -117,3 +97,38 @@ getWeakenErrorMessageAndCtx = getTypeCoercionErrorMessageAndCtx $
...
+
+getTypeCoercionErrorMessageAndCtx :: (Type -> TypedExpr -> String) -> TypeCoercionError -> (String, Ctx)
+getTypeCoercionErrorMessageAndCtx getUncoercableTypesMsg typeCoercionError = (fullErrorMsg, ctx)
+  where
+    (typesErrorMsg, ctxMsgs, ctx) = getUncoercableTypesMsgAndCtxMsgsAndCtx getUncoercableTypesMsg typeCoercionError
+    fullErrorMsg
+      | null ctxMsgs = typesErrorMsg
+      | otherwise = intercalate "\n\n" [typesErrorMsg, concatContextualMsgs ctxMsgs]
+
+-- | Takes a function for constructing a type coercion error message, and a `TypeCoercionError`.
```
Comment (Martinsos) [inline waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs:109]: I would first say what it does.

So:
```
For a given a type coercion error, constructs error message and its context.
```

Then you can continue similar to what you have, describing details of how that is done -> we are given a function that constructs the main error message, and what is exactly returned as context is a **list** of messages that describe the structure in which error occurred, ... -> you already have this part will written, I just wanted to suggest adding this "high level overview" sentence as the start of the comment.

File: waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs (hunk 9 above)
[the remark this answers is not in the document]
Comment (Martinsos) [reply waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs]: I don't have a specific rule! Certainly, if you want to test it, it can't be in `where`. So that is one hard rule. Other than that, what you feel good about. Personally, I don't have a strong preference here.

I would thought be consistent in naming: so if you used `ctxMsgs` in function above, I would also use `concatCtxMsgs` here.

File: waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs [hunk 13]
```diff
@@ -117,3 +97,38 @@ getWeakenErrorMessageAndCtx = getTypeCoercionErrorMessageAndCtx $
...
+--
+-- It recursively traverses the error stack and returns a tuple containing:
+-- - The original type coercion error message
+-- - An array of contextual messages further explaining the original error
+-- - The error's context
+getUncoercableTypesMsgAndCtxMsgsAndCtx :: (Type -> TypedExpr -> String) -> TypeCoercionError -> (String, [String], Ctx)
+getUncoercableTypesMsgAndCtxMsgsAndCtx getUncoercableTypesMsg (TypeCoercionError (WithCtx ctx texpr) t reason) =
+  case reason of
+    ReasonList e -> second3 ("In list element" :) $ getFurtherMsgsAndCtx e
```
Comment (Martinsos) [inline waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs:118]: "In list element" sounds a bit weird, since it could be the list element itself that is problematic, right?
So maybe "for list element" is better? Or just "in list"?
I wonder now if it was me who told you to change it this way :D? But if I did, I was wrong I think.

File: waspc/test/AnalyzerTest.hs [hunk 14]
```diff
@@ -239,10 +240,11 @@ spec_Analyzer = do
...
                                      "\n"
                                      [ "Type error:",
-                                       "  For dictionary field 'dependencies':",
-                                       "    For list element:",
-                                       "      Expected type: (string, string)",
-                                       "      Actual type:   (string, number)"
+                                       "  Expected type: (string, string)",
+                                       "  Actual type:   (string, number)",
+                                       "",
+                                       "  -> For dictionary field 'dependencies':",
```
Comment (Martinsos) [inline waspc/test/AnalyzerTest.hs:246]: Looking at this, would it make sense to further indent context error messages, to make it clear they are additional information?

Smth like
```
                                     [ "Type error:",
                                       "  Expected type: (string, string)",
                                       "  Actual type:   (string, number)",
                                       "",
                                       "    -> For dictionary field 'dependencies':",
                                       "      -> In list element"
```

**Review by Martinsos — APPROVED** [review]
Looking good @sodic ! Left couple minor comments, feel free to merge once you are happy with it.

File: waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs (hunk 12 above)
Comment (sodic) [reply waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs:109]: Definitely, I'll switch it up.

File: waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs (hunk 11 above)
Comment (sodic) [reply waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs:115]: Hm, I guess I thought I'd introduce the naming pattern:

- An **error message** is the string that describes the error.
- **Context messages** are strings describing the location (i.e., the context). They aren't necessarily error messages, as they can describe the context of anything (for example, a warning)
- **The Context** is the location of "the thing" described by the context message (of course, this name/concept already existed).

But that was pretty arbitrary and I didn't document it anywhere :smile: 

Perhaps a better name for _context messages_ is _context info_, I could then name the function one of the following:
- `getUncoercableTypesErrorMsgAndCtxInfoAndCtx`
- `getUncoercableTypesErrorMsgAndCtxInfoAndParsingCtx` - I'm not sure about this one since we're referring to the same thing with two different names. `Ctx` in `CtxInfo` and `ParsingCtx` are talking about the same `Ctx`.
- `getUncoercableTypesErrorMsgAndParsingCtxInfoAndParsingCtx`

Perhaps an even better solution is grouping the parsing context and its info messages into a same type, but this can probably wait for a different PR. I'd be happy to do it now if you think it makes sense, and if we can afford to spend a bit more time on this.

@Martinsos  What do you think?

File: waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs (hunk 13 above)
Comment (sodic) [reply waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs:118]: I'll go with "In list".

File: waspc/test/AnalyzerTest.hs (hunk 14 above)
Comment (sodic) [reply waspc/test/AnalyzerTest.hs:246]: I prefer it without the further indent, but can't really explain why. They're already indented under `Type Error`, and the empty line does a good-enough job of separating the additional info, I think. Indenting the first context message looks a bit weird to me.

I'd personally leave it like this., but I don't have a strong preference. I can change it if you do.

Comment (Martinsos) [reply waspc/test/AnalyzerTest.hs:246]: Ok, no worries, let's leave it as it is then!

File: waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs (hunk 11 above)
Comment (Martinsos) [reply waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs:117]: The thing is, it is not the same Ctx -> One thing is Parser.Ctx, while another thing are these error context messages.

I would propose following naming:
1. Error message -> string that describes the core part of error.
2. Error context messages (or Error context info) -> additional messages that provide more info about the error, mostly about its surroundings (context) in the Wasp lang AST. These messages are aware that we are dealing with an error, in a sense.
3. Parsing context (Parser.Ctx) -> information about where this piece of code is coming from, regarding the source file, where it was parsed from. Will be also important for LSP later. This information doesn't know anything about errors as a concept and is present in all our intermediate representations.

The reason I would not group (2) with (3) is that (3) is more general and present through all IRs, while (2) is relatively specific for this phase/IR, maybe one more (Evaluator). At least for now -> maybe more generalized version of it will emerge with time, but I don't think we are there yet.

File: waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs [hunk 15]
```diff
@@ -114,8 +114,11 @@ getTypeCoercionErrorMessageAndCtx getUncoercableTypesMsg typeCoercionError = (fu
 -- It takes two arguments:
 --  - A function for constructing a type coercion error message
 --  - A `TypeCoercionError` to process
-getUncoercableTypesMsgAndCtxMsgsAndCtx :: (Type -> TypedExpr -> String) -> TypeCoercionError -> (String, [String], Ctx)
-getUncoercableTypesMsgAndCtxMsgsAndCtx getUncoercableTypesMsg (TypeCoercionError (WithCtx ctx texpr) t reason) =
+getUncoercableTypesErrorMsgAndCtxInfoAndParsingCtx ::
```
Comment (Martinsos) [inline waspc/src/Wasp/Analyzer/TypeChecker/TypeError.hs:117]: Hehe best name ever :D

File: waspc/src/Wasp/Analyzer/Evaluator/EvaluationError.hs [hunk 16]
```diff
@@ -62,57 +59,70 @@ data EvaluationParseError
 mkEvaluationError :: Ctx -> EvaluationError' -> EvaluationError
 mkEvaluationError ctx e = EvaluationError $ WithCtx ctx e
 
+concatCtxMessages :: [String] -> String
+concatCtxMessages [] = ""
+concatCtxMessages msgChain = prefix ++ foldr1 appendMsg msgChain
+  where
+    prefix = "-> "
+    appendMsg currMsg = (++) (currMsg ++ ":\n") . indent 2 . (prefix ++)
```
Comment (Martinsos) [inline waspc/src/Wasp/Analyzer/Evaluator/EvaluationError.hs:67]: Ok, so this is part that is common between TypeError and EvaluationError, and it knows notihng about them, it just handles strings which are context errors.

I think this one we can externalize right now, without much thinking. I am not sure where to put it hm -> Analyzer/ErrorCtx.hs ?

Comment (sodic) [reply waspc/src/Wasp/Analyzer/Evaluator/EvaluationError.hs:67]: Yes, but the function below (`getErrorMessageAndCtx`) is pretty similar as well. I could extract that one too, although it would require a bit of rearranging.

Comment (Martinsos) [reply waspc/src/Wasp/Analyzer/Evaluator/EvaluationError.hs]: Yeah but it has different types in the signature right? And it is so short that I wouldn't bother with it for now. Unless you have some interesting idea, but I think you won't gain much by trying to extract it.

File: waspc/src/Wasp/Analyzer/ErrorMessage.hs [hunk 17]
```diff
@@ -0,0 +1,19 @@
...
+  )
+where
+
+import Data.List (intercalate)
+import Wasp.Util (indent)
+
+makeFullErrorMsg :: String -> [String] -> String
+makeFullErrorMsg errorMsg errorCtxMsgs
+  | null errorCtxMsgs = errorMsg
+  | otherwise = intercalate "\n\n" [errorMsg, concatCtxMessages errorCtxMsgs]
```
Comment (Martinsos) [inline waspc/src/Wasp/Analyzer/ErrorMessage.hs:12]: Maaaaybe simpler, but do whatever you like:

```suggestion
makeFullErrorMsg errorMsg errorCtxMsgs = 
  errorMsg ++ (if null errorCtxMsgs then "" else "\n\n" ++ concatCtxMessages errorCtxMsgs)
```

**Review by Martinsos — APPROVED** [review]
Left a tiny comment, but I think this is it, looks good :)!!

File: waspc/src/Wasp/Analyzer/ErrorMessage.hs (hunk 17 above)
Comment (sodic) [reply waspc/src/Wasp/Analyzer/ErrorMessage.hs]: I have to disagree with this one - I prefer the variant with guards: less concatenation, seems more declarative (kind of reminds me of a math formula) and easier to edit.

File: waspc/test/Analyzer/Evaluation/EvaluationErrorTest.hs [hunk 18]
```diff
@@ -1,27 +1,80 @@
...
+nestEvalErrors bottomErr wrapperErrs = foldr wrap bottomErr wrapperErrs
+  where
+    wrap evalErrorCtx = mkEvaluationError ctx1 . WithEvalErrorCtx evalErrorCtx
+
 spec_EvaluationError :: Spec
 spec_EvaluationError = do
   describe "Analyzer.Evaluator.EvaluationError" $ do
     describe "getErrorMessageAndCtx works correctly for" $ do
+      let expectedTypeError = mkEvaluationError ctx1 $ ExpectedType NumberType StringType
+      let expectedTypeErrorMsg = "Expected type: number\nActual type:   string"
```
Comment (sodic) [inline waspc/test/Analyzer/Evaluation/EvaluationErrorTest.hs:23]: I extracted these two because I reused them in multiple tests, is that a normal thing to do (note that their original test is now only an equality check, the code is actually executed outside)? @Martinsos

File: waspc/src/Wasp/Analyzer/ErrorMessage.hs (hunk 17 above)
Comment (Martinsos) [reply waspc/src/Wasp/Analyzer/ErrorMessage.hs]: Ha ok, no worries! What I liked about the second option is that it reads as "Full error messages consists of error message + something, and that something is nothing if no error ctx messages or if there are some, they are concatenated".
So this part of errorMessage + smth is what I liked.

While in the current code, it is:
1. if no error ctx messages, then it is error message.
2. if error ctx messages, then it is error message + concatenated context error messages.
So in a way, there is duplication, which is this logic of putting error message in front, and then context error messages in the back.

Maybe middle ground is:
```hs
makeFullErrorMsg errorMsg errorCtxMsgs = errorMsg ++ case errorCtxMsgs of
  [] -> ""
  msgs -> "\n\n" ++ concatCtxMessages msgs
```

At the end, this piece of code is so small that all goes, so the whole discussion is a bit trivial :D, but maybe explaining the way of thinking is still interesting.

File: waspc/test/Analyzer/Evaluation/EvaluationErrorTest.hs [hunk 19]
```diff
@@ -1,27 +1,80 @@
...
 import Test.Tasty.Hspec
 import Wasp.Analyzer.Evaluator.EvaluationError
+import Wasp.Analyzer.Parser.Ctx
 import Wasp.Analyzer.Type (Type (..))
 
+ctx1 :: Ctx
+ctx1 = ctx (1, 4) (2, 5)
+
+nestEvalErrors :: EvaluationError -> [EvalErrorCtx] -> EvaluationError
+nestEvalErrors bottomErr wrapperErrs = foldr wrap bottomErr wrapperErrs
```
Comment (Martinsos) [inline waspc/test/Analyzer/Evaluation/EvaluationErrorTest.hs:14]: I would rename it to `wrapEvalError`, since you already use `wrap` so much!

File: waspc/test/Analyzer/Evaluation/EvaluationErrorTest.hs [hunk 20]
```diff
@@ -1,27 +1,80 @@
...
+
       it "ExpectedTupleType error" $ do
-        let ctx1 = ctx (1, 4) (2, 5)
-        let err = mkEvaluationError ctx1 $ ExpectedTupleType 3 StringType
-        getErrorMessageAndCtx err `shouldBe` ("Expected a tuple of size 3.\nActual type: string", ctx1)
+        let expectedTupleTypeError = mkEvaluationError ctx1 $ ExpectedTupleType 3 StringType
+        let expectedTupleTypeErrorMsg = "Expected a tuple of size 3.\nActual type: string"
+        getErrorMessageAndCtx expectedTupleTypeError `shouldBe` (expectedTupleTypeErrorMsg, ctx1)
+
+      it "ExpectedType error nested in WithEvalContextError" $ do
```
[the remark this answers is not in the document]
Comment (Martinsos) [reply waspc/test/Analyzer/Evaluation/EvaluationErrorTest.hs:41]: I agree, no need to overtest this, as long as you covered some reasonable paths we are good.

**Review by Martinsos — APPROVED** [review]

**Review by sodic — COMMENTED** [review]
@Martinsos I went through the previous comments and I think we covered everything. You can take a look if you want and then I'll merge it!

File: waspc/src/Wasp/Analyzer/ErrorMessage.hs [hunk 21]
```diff
@@ -3,13 +3,11 @@ module Wasp.Analyzer.ErrorMessage
...
 
-import Data.List (intercalate)
 import Wasp.Util (indent)
 
 makeFullErrorMsg :: String -> [String] -> String
-makeFullErrorMsg errorMsg errorCtxMsgs
-  | null errorCtxMsgs = errorMsg
-  | otherwise = intercalate "\n\n" [errorMsg, concatErrorCtxMsgs errorCtxMsgs]
+makeFullErrorMsg errorMsg errorCtxMsgs =
+  errorMsg ++ (if null errorCtxMsgs then "" else concatErrorCtxMsgs errorCtxMsgs)
```
Comment (Martinsos) [inline waspc/src/Wasp/Analyzer/ErrorMessage.hs]: Ha, you did this at the end! I hope you were feeling fine with it, certainly didn't have to do it because of me, as I said it was just an idea, I am ok with both.

**Review by Martinsos — APPROVED** [review]
LGTM!

File: waspc/src/Wasp/Analyzer/ErrorMessage.hs (hunk 21 above)
Comment (sodic) [reply waspc/src/Wasp/Analyzer/ErrorMessage.hs]: No worries! As you said, it's a pretty trivial thing so it really doesn't matter. And you sold it to me with the reasoning (besides, it also doesn't require an import.
