### PR TITLE
Fixes `sodium-native` bug to support Heroku deploys

### LINKED ISSUE #719: Unable to deploy to Heroku due to `sodium-native` bug
We are currently unable to deploy Wasp apps to Heroku, as one of our dependencies (`secure-password`) has a new bug in one of its dependencies: https://github.com/sodium-friends/sodium-native/issues/160

The current workaround is to add this dependency to your .wasp file:
```
app MyApp {
  title: "My app",
  // ...
  dependencies: [
    // ...
    ("sodium-native", "3.3.0") 👈
  ]
)
```

### PR DESCRIPTION
**Pull request by shayneczyzewski**
# Description

This change adds support for `"overrides"` in our `package.json` file, and specifically fixes a `sodium-native` bug that is preventing users from deploying to Heroku right now.

Refs:
- https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides
- https://github.com/sodium-friends/sodium-native/issues/160

Fixes #719 

## Type of change

Please select the option(s) that is more relevant.

- [ ] Code cleanup
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by shayneczyzewski** [comment]
Is this the approach you had in mind @Martinsos?

File: waspc/src/Wasp/Generator/ServerGenerator.hs [hunk 1]
```diff
@@ -252,3 +257,32 @@ patchesRequiredByPassport spec =
...
+    buildOverrideData :: (String, String, String, Bool) -> Aeson.Value
+    buildOverrideData (packageName, dependencyName, dependencyVersion, lastElement) =
+      object
+        [ "packageName" .= packageName,
+          "dependencyName" .= dependencyName,
+          "dependencyVersion" .= dependencyVersion,
+          "last" .= lastElement
+        ]
+
+    designateLastElement :: [(String, String, String)] -> [(String, String, String, Bool)]
```
Comment (shayneczyzewski) [inline waspc/src/Wasp/Generator/ServerGenerator.hs:284]: Has to be some cleaner way to do this, but couldn't quickly think of it.

File: waspc/src/Wasp/Generator/ServerGenerator.hs [hunk 2]
```diff
@@ -116,6 +120,7 @@ npmDepsForWasp spec =
             ("morgan", "~1.10.0"),
             ("@prisma/client", show prismaVersion),
             ("jsonwebtoken", "^8.5.1"),
+            -- NOTE: secure-password has a package.json override for sodium-native.
```
Comment (shayneczyzewski) [inline waspc/src/Wasp/Generator/ServerGenerator.hs:123]: Ideally we'd have a better way to connect the dots here, but a comment should hopefully suffice in meantime.

File: waspc/src/Wasp/Generator/ServerGenerator.hs (hunk 1 above)
Comment (shayneczyzewski) [reply waspc/src/Wasp/Generator/ServerGenerator.hs:284]: Yeah, true. I was thinking `zip` as well, but figured the shape got a bit stranger with that at the end. Plus, the fact we need the _last_ to be different would require doing a `True` first, then an infinite list of `False`, then reversing things a few times.

Unfortunately, if we leave a trailing comma, VS Code will put a red line under it since it is not valid JSON.

I will just go ahead and leave it as is for now since it is so localized. Thanks! 👍🏻
