### PR TITLE
Check invalid declaration names in ts spec

### LINKED ISSUE #2916: Improve Invalid Route Name Handling
**Describe the bug**
Naming a route with a space does not throw a Wasp error. Rather, it causes a syntax error in the `.wasp/out/sdk/wasp/client/router/index.ts` file: `error TS1005: ',' expected.` It's not hard to figure out why once you visit the file:
```
  Home Page: {
    to: "/",
    build: (
      options?:
      OptionalRouteOptions
    ) => interpolatePath(
        
        "/",
        undefined,
        options?.search,
        options?.hash
      ),
  },
```

Wasp should throw an error when attempting to add a route with a space rather than let it continue and fail silently.

**To Reproduce**

1. Create a route with a space in its name.
2. Run `wasp start` and wait for the SDK to attempt to build.
3. See TS error.

**Expected behavior**
A Wasp-generated error explaining there cannot be spaces in a route name.

### PR DESCRIPTION
**Pull request by sodic**
## Description

Fixes #2916 and then some.

Here's how it looks like:

image

## Type of change

- [ ] **🔧 Just code/docs improvement** 
- [x] **🐞 Bug fix** 
- [ ] **🚀 New/improved feature** 
- [ ] **💥 Breaking change** 

## Checklist

- [x] I tested my change in a Wasp app to verify that it works as intended.

- 🧪 Tests and apps:

  - [x] I added **unit tests** for my change. 
  - [x] _(if you fixed a bug)_ I added a **regression test** for the bug I fixed. 
  - [ ] _(if you added/updated a feature)_ I added/updated **e2e tests** in `examples/kitchen-sink/e2e-tests`.
  - [ ] _(if you added/updated a feature)_ I updated the **starter templates** in `waspc/data/Cli/templates`, as needed.
  - [ ] _(if you added/updated a feature)_ I updated the **example apps** in `examples/`, as needed.
    - [ ] _(if you updated `examples/tutorials`)_ I updated the tutorial in the docs (and vice versa).

- 📜 Documentation:

  - [ ] _(if you added/updated a feature)_ I **added/updated the documentation** in `web/docs/`.

- 🆕 Changelog: _(if change is more than just code/docs improvement)_
  - [x] I updated `waspc/ChangeLog.md` with a **user-friendly** description of the change.
  - [ ] _(if you did a breaking change)_ I added a step to the current **migration guide** in `web/docs/migration-guides/`.
  - [ ] I **bumped the `version`** in `waspc/waspc.cabal` to reflect the changes I introduced.

### CODE REVIEW

File: waspc/tests/AppSpec/ValidTest.hs [hunk 1]
```diff
@@ -453,6 +454,47 @@ spec_AppSpecValid = do
...
+        testInvalidDeclName makeBasicPageDecl "Import"
+        testInvalidDeclName makeBasicJobDecl "1st job"
+        testInvalidDeclName makeBasicQueryDecl "my-query"
+        testInvalidDeclName makeBasicActionDecl "my action"
+
+      describe "returns no error for valid identifiers" $ do
+        testValidDeclName makeBasicPageDecl "Import"
+        testValidDeclName makeBasicJobDecl "_1stJob"
+        testValidDeclName makeBasicQueryDecl "my_query"
+        testValidDeclName makeBasicActionDecl "myAction"
```
Comment (sodic) [inline waspc/tests/AppSpec/ValidTest.hs:481]: These are the tests related to the new logic. The other tests are for old code and I added them in passing.

File: waspc/src/Wasp/AppSpec/Valid.hs [hunk 2]
```diff
@@ -335,6 +337,42 @@ validateDeclarationNames spec =
...
+        - This is where we keep similar app spec validations.
+        - It reuses the actual lexer instead of duplicating its rules in
+          TypeScript (and potential future spec variants)
+      -}
+      let invalidDeclNames = filter (not . isValidWaspIdentifier) $ map getDeclName $ AS.decls spec
+          declNameRules =
+            [ "must start with a letter or an underscore",
+              "must contain only letters, numbers, or underscores",
+              "must not be a Wasp keyword"
+            ]
```
Comment (sodic) [inline waspc/src/Wasp/AppSpec/Valid.hs:366]: There's some apparent duplication here and in `ProjectDescription#parseWaspProjectNameIntoAppName`.

I tried to find a way to remove it but it was too fiddly, the main reason being that the `parseWaspProjectNameIntoAppName` additionally accepts dashes. Weaving that extra bit of information into the shared message while satisfying both formats was more trouble than it was worth, so I left it as is.

File: waspc/tests/AppSpec/ValidTest.hs [hunk 3]
```diff
@@ -453,6 +454,47 @@ spec_AppSpecValid = do
           `shouldBe` [ Valid.GenericValidationError
                          "You must have at least one route in your app. You can add it using the 'route' declaration."
                      ]
+
+    describe "invalid declaration names validation" $ do
+      let testInvalidDeclName makeDecl invalidName = it invalidName $ do
+            let decl = makeDecl invalidName
+            let errors = ASV.validateAppSpec (basicAppSpec {AS.decls = [basicAppDecl, decl, basicRouteDecl]})
+            case errors of
+              [err] -> invalidName `isInfixOf` show err `shouldBe` True
```
Comment (sodic) [inline waspc/tests/AppSpec/ValidTest.hs:463]: I didn't want to match the entire string because it seemed to brittle.

File: waspc/src/Wasp/AppSpec/Valid.hs (hunk 2 above)
Comment (FranjoMindek) [reply waspc/src/Wasp/AppSpec/Valid.hs:366]: I would say those two are 2 different cases then, and should be treated so.

File: waspc/src/Wasp/AppSpec/Valid.hs [hunk 4]
```diff
@@ -335,6 +337,42 @@ validateDeclarationNames spec =
...
+       in case invalidDeclNames of
+            [] -> []
+            _ ->
+              [ GenericValidationError $
+                  intercalate "\n" $
+                    ("Please rename: " ++ intercalate ", " invalidDeclNames ++ ". Each declaration name:")
```
Comment (FranjoMindek) [inline waspc/src/Wasp/AppSpec/Valid.hs]: Only thing I would so is to make `parseWaspProjectNameIntoAppName` error message and this one be more similar. To be consistent with out messaging.

So pick one from `it can` and `must`, etc.

File: waspc/ChangeLog.md [hunk 5]
```diff
@@ -29,6 +29,7 @@ Remember to check out the [migration guide](https://wasp.sh/docs/migration-guide
 - Fixed an issue where if Wasp was installed from npm, `wasp new` would not work correctly. ([#3585](https://github.com/wasp-lang/wasp/pull/3585))
 - Fixed an issue where the `Link` component might not update with the values of `search` and `hash` (by @Pipboyguy). ([#3633](https://github.com/wasp-lang/wasp/pull/3633))
 - We now support Railway CLI v4.18.1 and greater on `wasp deploy railway`. ([#3667](https://github.com/wasp-lang/wasp/pull/3667))
+- Wasp TS spec now validates declaration names ([#3721](https://github.com/wasp-lang/wasp/pull/3721))
```
Comment (FranjoMindek) [inline waspc/ChangeLog.md]:
```suggestion
- Wasp TS spec now validates declaration names. ([#3721](https://github.com/wasp-lang/wasp/pull/3721))
```

File: waspc/src/Wasp/AppSpec/Valid.hs [hunk 6]
```diff
@@ -297,7 +298,8 @@ validateUniqueDeclarationNames spec =
 validateDeclarationNames :: AppSpec -> [ValidationError]
 validateDeclarationNames spec =
   concat
-    [ capitalizedOperationsErrorMessage,
+    [ invalidDeclNamesErrorMessage,
```
Comment (FranjoMindek) [inline waspc/src/Wasp/AppSpec/Valid.hs]: Okay I got a bit confused with the names down in the tests because of this `invalidDeclNamesErrorMessage` name.

We have following defined lines in our tests:
- the tests section - `invalid declaration names validation`
- helper functions - `testInvalidDeclName`, `testValidDeclName`


Makes it seem like tests test only this specific scenario, but it is really not. It's testing the whole `validateDeclarationNames`.  Let's clear this up a bit.

`invalid declaration names validation` -> maybe `declaration names validation` or `validateDeclarationNames` if it seems like we validating that specific function?

`invalidDeclNamesErrorMessage` seems fine. I don't know if we can change it really.
