### PR TITLE
Do not return a 401 error on unauthorized requests to `/auth/me`

### LINKED ISSUE #1880: Find a way to avoid getting 401 from server when user is not logged in
In Wasp, when on a page that requires auth user, client will ask server to get the user via `auth/me` route, which will then return `401` if user is not authenticated. We just ignore that 401 and go with it.

The thing is, this 401:
1. Confuses people, they think it is a potential issue (we had person asking about it in Discord).
2. Confuses Cypress (e2e testing): it thinks error happened and test fails unless you explicitly set it to not fail. https://discord.com/channels/686873244791210014/1216893853890510908/1216893853890510908

### PR DESCRIPTION
**Pull request by cprecioso**
### Description

Fixes #1880 

`/auth/me` will not return a 401 code for a user who is not logged in, but a 200 with `null`.
Thus, `useAuth()` will not print an error to the console when it's called when not logged in. The return value for `useAuth()` stays the same.

The `/auth/me` endpoint is not explicitly documented anywhere, so I didn't treat it as a breaking change, but it could arguably be one.

### Select what type of change this PR introduces:
1. [ ] **Just code/docs improvement** (no functional change).
2. [x] **Bug fix** (non-breaking change which fixes an issue).
3. [ ] **New feature** (non-breaking change which adds functionality).
4. [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected).

### Update Waspc ChangeLog and version if needed
If you did a bug fix, new feature, or breaking change, that affects waspc, make sure you satisfy the following:
1. [x] I updated [ChangeLog.md](https://github.com/wasp-lang/wasp/blob/main/waspc/ChangeLog.md) with description of the change this PR introduces.
2. [ ] I bumped waspc version in [waspc.cabal](https://github.com/wasp-lang/wasp/blob/main/waspc/waspc.cabal) to reflect changes I introduced, with regards to the version of the latest wasp release, if the bump was needed.

### Update example apps if needed
If you did code changes and added a new feature or modified an existing feature, make sure you satisfy the following:
1. [ ] I updated `waspc/examples/todoApp` as needed (updated modified feature or added new feature) and manually checked it works correctly.
2. [x] I updated `waspc/headless-test/examples/todoApp` and its e2e tests as needed (updated modified feature and its tests or added new feature and new tests for it).

### CODE REVIEW

File: waspc/data/Generator/templates/sdk/wasp/auth/useAuth.ts [hunk 1]
```diff
@@ -25,14 +25,10 @@ function createUserGetter(): Query<void, AuthUser | null> {
       const userData = superjsonDeserialize<AuthUserData | null>(response.data)
       return makeAuthUserIfPossible(userData)
     } catch (error) {
-      if (error.response?.status === 401) {
-        return null
-      } else {
-        throw handleApiError(error)
-      }
```
Comment (cprecioso) [inline waspc/data/Generator/templates/sdk/wasp/auth/useAuth.ts:32]: If we get a 401 now, it is truly unexpected, so we let it throw.

File: waspc/ChangeLog.md [hunk 2]
```diff
@@ -6,6 +6,10 @@
 
 - In the `usernameAndPassword` authentication method, the function `login()` imported from `wasp/client/auth` now accepts an object with `username` and `password` instead of two separate arguments ([#2598](https://github.com/wasp-lang/wasp/pull/2598))
 
+### 🐞 Bug fixes
+
+- Calling `useAuth()` when the user is not logged in will not fail the request, only return `null` ([#2689](https://github.com/wasp-lang/wasp/pull/2689))
```
Comment (sodic) [inline waspc/ChangeLog.md:11]: Hmm, is this a breaking change too? Could users have relied on this behavior?

File: waspc/e2e-test/test-outputs/waspComplexTest-golden/waspComplexTest/.wasp/out/sdk/wasp/auth/useAuth.ts [hunk 3]
```diff
@@ -24,14 +24,10 @@ function createUserGetter(): Query<void, AuthUser | null> {
       const userData = superjsonDeserialize<AuthUserData | null>(response.data)
```
Comment (sodic) [inline waspc/e2e-test/test-outputs/waspComplexTest-golden/waspComplexTest/.wasp/out/sdk/wasp/auth/useAuth.ts:24]: Interesting that we already had a system and type signatures in place for returning `null`.

@infomiho @cprecioso Do you guys know if we ever returned `null` in the response? I forgot.

**Review by sodic — APPROVED** [review]
Nice work!

Seems simple enough.
I'm just curios whether we should document it as a breaking change.

File: waspc/e2e-test/test-outputs/waspComplexTest-golden/waspComplexTest/.wasp/out/sdk/wasp/auth/useAuth.ts (hunk 3 above)
Comment (cprecioso) [reply waspc/e2e-test/test-outputs/waspComplexTest-golden/waspComplexTest/.wasp/out/sdk/wasp/auth/useAuth.ts:24]: I checked blame, and not that I can see

**Comment by cprecioso** [comment]
@sodic replied to your comments

File: waspc/ChangeLog.md (hunk 2 above)
Comment (sodic) [reply waspc/ChangeLog.md:29]: Fair enough, no breaking change then.

If someone does rely on it and we break their code, we'll teach them about [Hyrum's law](https://www.hyrumslaw.com/) as an aplogy :)

File: waspc/e2e-test/test-outputs/waspComplexTest-golden/waspComplexTest/.wasp/out/sdk/wasp/auth/useAuth.ts (hunk 3 above)
Comment (sodic) [reply waspc/e2e-test/test-outputs/waspComplexTest-golden/waspComplexTest/.wasp/out/sdk/wasp/auth/useAuth.ts:24]: Ok, I'm just curious why it's already built for `null`, @infomiho Probably knows.

Let's wait for him and then merge it.

Comment (infomiho) [reply waspc/e2e-test/test-outputs/waspComplexTest-golden/waspComplexTest/.wasp/out/sdk/wasp/auth/useAuth.ts:24]: Hm, I'm not really sure why we had `null` there. Looking at the implementation of the endpoint, it didn't return the `req.user` if it was falsy, so it couldn't return `null` in the success case. I probably made a mistake and that's it :)

**Comment by infomiho** [comment]
I think there might be one extra code path to consider, the `auth` middleware has this line: https://github.com/wasp-lang/wasp/blob/7cfd2b4458db649d8e87218a909a21fa6def3794/waspc/data/Generator/templates/sdk/wasp/core/auth.ts#L31

If a user hits the `/auth/me` endpoint with a stale session, they will get a 401 error. That seems fine and expected to me. I just wanted to mention that and if we feel that's fine, this PR is ready to be merge IMHO.

**Review by infomiho — CHANGES_REQUESTED** [review]
I tried running the `todoApp` and it won't load for me: 

https://github.com/user-attachments/assets/d640a3d5-9960-409d-91c9-f07f20e5f1ef

Let's always please test out the changes we do with the `todoApp`.

File: waspc/data/Generator/templates/server/src/routes/auth/me.ts [hunk 4]
```diff
@@ -1,11 +1,10 @@
 import { serialize as superjsonSerialize } from 'superjson'
 import { handleRejection } from 'wasp/server/utils'
-import { createInvalidCredentialsError } from 'wasp/auth/utils'
 
 export default handleRejection(async (req, res) => {
   if (req.user) {
     return res.json(superjsonSerialize(req.user))
   } else {
-    throw createInvalidCredentialsError()
+    return res.json(null)
```
Comment (infomiho) [inline waspc/data/Generator/templates/server/src/routes/auth/me.ts:8]:
```suggestion
    return res.json(superjsonSerialize(null))
```

Maybe this will get rid of the error `TypeError: payload is null`

Comment (cprecioso) [reply waspc/data/Generator/templates/server/src/routes/auth/me.ts:8]: Yes!

**Comment by cprecioso** [comment]
> I'm not really sure how the CI passed
I'm also not sure... I was testing the changes with a local app and it worked, so I didn't think to also test with todoApp as the CI would catch it. 😕

Anyway, I fixed it now @infomiho, tested in the todoApp too

**Review by infomiho — APPROVED** [review]
Good to go
