### PR TITLE
Fix Railway service variable references with special characters

### LINKED ISSUE #3513: Other service variable references on Railway need to be quotes when service name has numbers
Wasp version: 0.20.0

I created a new project with the name `kitchen-sink-0.20.0` and the deployment of the server app failed because the `WASP_WEB_CLIENT_URL` variable value was wrong. 

It turns out the we set the value to:

`https://${{kitchen-sink-0.20.0-client.RAILWAY_PUBLIC_DOMAIN}}` 

and Railway needs the value to be:

`https://${{"kitchen-sink-0.20.0-client".RAILWAY_PUBLIC_DOMAIN}}`

Noticed the quotes around the service name.

### PR DESCRIPTION
**Pull request by cprecioso**
## Description

When a service name contains special characters (e.g., hyphens with numbers like "kitchen-sink-0.20.0"), Railway requires the service name to be quoted in variable references. This fix refactors `getRailwayEnvVarValueReference` to accept an explicit service parameter and automatically quote service names when needed, enabling successful deployments with project names like `kitchen-sink-0.20.0`.

They now resolve correctly:

<table>
<tr>
 <td>image
 <td>image
</table>

Fixes #3513

## Type of change

- [x] **🐞 Bug fix** 

## Checklist

- [x] I tested my change in a Wasp app to verify that it works as intended.

- 🧪 Tests and apps:

  - [ ] I added **unit tests** for my change.
  - [ ] _(if you fixed a bug)_ I added a **regression test** for the bug I fixed.
  - [ ] _(if you added/updated a feature)_ I added/updated **e2e tests** in `examples/kitchen-sink/e2e-tests`.
  - [ ] _(if you added/updated a feature)_ I updated the **starter templates** in `waspc/data/Cli/templates`, as needed.
  - [ ] _(if you added/updated a feature)_ I updated the **example apps** in `examples/`, as needed.
    - [ ] _(if you updated `examples/tutorials`)_ I updated the tutorial in the docs (and vice versa).

- 📜 Documentation:

  - [ ] _(if you added/updated a feature)_ I **added/updated the documentation** in `web/docs/`.

- 🆕 Changelog: _(if change is more than just code/docs improvement)_
  - [x] I updated `waspc/ChangeLog.md` with a **user-friendly** description of the change.
  - [ ] _(if you did a breaking change)_ I added a step to the current **migration guide** in `web/docs/migration-guides/`.
  - [ ] I **bumped the `version`** in `waspc/waspc.cabal` to reflect the changes I introduced.

### CODE REVIEW

**Comment by infomiho** [comment]
SCR-20260129-ixcd

They also fixed a thing on their side 😂

File: waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts [hunk 1]
```diff
@@ -173,12 +173,15 @@ async function setupServer({
   const serverBuildDir = getServerBuildDir(options.waspProjectDir);
   const railwayCli = createCommandWithCwd(options.railwayExe, serverBuildDir);
 
-  const clientUrl = `https://${getRailwayEnvVarValueReference(`${clientServiceName}.RAILWAY_PUBLIC_DOMAIN`)}`;
+  const clientUrl = `https://${getRailwayEnvVarValueReference(
```
Comment (infomiho) [inline waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts:176]: NIce, reminds of this idea for a refactor be explicit about the service: https://github.com/wasp-lang/wasp/issues/3421

File: waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts [hunk 2]
```diff
@@ -224,6 +227,20 @@ async function setupClient({
...
-function getRailwayEnvVarValueReference(name: string): string {
-  return "${{" + name + "}}";
+function getRailwayEnvVarValueReference(
+  name: string,
+  { service }: { service?: string } = {},
+): string {
+  // Railway variable references have the format ${{VARIABLE}} for local variables
+  // or ${{serviceName.VARIABLE}} for cross-service references.
+  // When the service name contains special characters (like hyphens with numbers),
+  // Railway requires it to be quoted: ${{"service-name".VARIABLE}}
```
Comment (infomiho) [inline waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts:237]: This part of the comment might be better suited above `JSON.stringify`

File: waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts [hunk 3]
```diff
@@ -224,6 +227,20 @@ async function setupClient({
...
+
+  const parts = [name];
+
+  if (service) {
+    parts.unshift(JSON.stringify(service));
```
Comment (infomiho) [inline waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts]: Can we comment on the effects of using `JSON.stringify` on a string. Are we using a cannon to kill a fly? 😄

**Comment by cprecioso** [comment]
> They also fixed a thing on their side 😂

So this is not needed anymore?
Btw idk why I'm not able to get any answer from support and you can 🤦‍♂️

File: waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts (hunk 1 above)
Comment (cprecioso) [reply waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts:176]: Mmm I'd say that issue is kind of solved already by this PR no?

File: waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts (hunk 3 above)
Comment (cprecioso) [reply waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts]: > Are we using a cannon to kill a fly?

funny, i don't think that is common in english so i guess it's translated from croatian, but we have the same saying in spanish 😂

Comment (cprecioso) [reply waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts]: > Can we comment on the effects of using JSON.stringify on a string

is this not well-known usage? i've always used it (and is well suited for) quoting and escaping strings in code generation. i didn't think this would require an explanation, but i might be wrong

File: waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts (hunk 2 above)
Comment (cprecioso) [reply waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts:237]: i don't agree, i think it's really commenting on the whole reasoning for the following four lines of function body 😁

File: waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts (hunk 1 above)
Comment (infomiho) [reply waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts:176]: It went a bit higher and talked about introducing a concept of a service context that should be useful throughout the deployment process. I think what you did here is a great start 😄

**Comment by infomiho** [comment]
> So this is not needed anymore?

It was two bugs, ours and theirs, they fixed theirs, we are fixing ours in this PR :)

File: waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts (hunk 3 above)
Comment (infomiho) [reply waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts]: It wasn't well know to me 😄

Comment (cprecioso) [reply waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts]: done

**Comment by cprecioso** [comment]
@infomiho ready for re-review

File: waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts [hunk 4]
```diff
@@ -224,6 +227,21 @@ async function setupClient({
   waspSays("Client setup complete!");
 }
 
-function getRailwayEnvVarValueReference(name: string): string {
-  return "${{" + name + "}}";
+function getRailwayEnvVarValueReference(
+  name: string,
+  { service }: { service?: string } = {},
```
Comment (infomiho) [inline waspc/data/packages/deploy/src/providers/railway/commands/setup/setup.ts]: I know this is a late comment but I realised this is more of a `serviceName` 😄 

RAW
