### PR TITLE
Fixes blog horizontal scroll

### LINKED ISSUE #3327: Horizontal scroll in website
**Describe the bug**
Blog listing pages in our website display a horizontal scroll even when there's no extra content on the horizontal axis.

This happens on any page using the blog post list layout:
- Main blog page: https://wasp.sh/blog
- Tag listing page: https://wasp.sh/blog/tags/wasp

**To Reproduce**

1. Go to one of the above linked pages
2. See there's a scrollbar on the bottom

**Expected behavior**
There shouldn't be a scrollbar or horizontal content

**Screenshots**

Image

**Desktop (please complete the following information):**

- OS: macOS 26
- Browser: Arc, Chrome, Safari, Firefox
- Version: Latest of everything

**Smartphone (please complete the following information):**

**Additional context**
We should check that our layout is up-to-date with the latest one from Docusarus

### PR DESCRIPTION
**Pull request by infomiho**
## Description

Fixes #3327 

### What was the cause? 

The `BlogLayout` component was used for both list of blog posts and single blog post. The layout used the `row` class **always** which had `-16px` horizontal margin but used `container` class **only on single blog post page**. The `container` class and `row` classes are meant to be used **together** because the `container`'s `16px` padding neutralizes the negative `16px` margin of the `row`.

The list page didn't want to use the container so the hero section can be 100% width, so I've now made it explicit that there are two layouts: `BlogPostsLayout` and `SingleBlogPostLayout`.

## Type of change

- [ ] **🔧 Just code/docs improvement** 
- [x] **🐞 Bug fix** 
- [ ] **🚀 New/improved feature** 
- [ ] **💥 Breaking change** 

## Checklist

- [ ] I tested my change in a Wasp app to verify that it works as intended.

- 🧪 Tests:

  - [ ] I added **unit tests** for my change. 
  - [ ] _(if you fixed a bug)_ I added a **regression test** for the bug I fixed. 
  - [ ] _(if you added/updated a feature)_ I added/updated **e2e tests** at `examples/kitchen-sink/e2e-tests`.
  - [ ] _(if you added/updated a feature)_ I updated the **starter templates** at `waspc/data/Cli/templates`, as needed.

- 📜 Documentation:

  - [ ] _(if you added/updated a feature)_ I **added/updated the documentation** in `web/docs/`.

- 🆕 Changelog: _(if change is more than just code/docs improvement)_
  - [ ] I updated `waspc/ChangeLog.md` with a **user-friendly** description of the change.
  - [ ] _(if you did a breaking change)_ I added a step to the current **migration guide** at `web/docs/migration-guides/`.
  - [ ] I **bumped the `version`** in `waspc/waspc.cabal` to reflect the changes I introduced.

### CODE REVIEW

File: web/src/components/Nav/index.jsx [hunk 1]
```diff
@@ -2,7 +2,6 @@ import Link from "@docusaurus/Link";
 import { useRef, useState } from "react";
 import { Star } from "react-feather";
 import Transition from "../../lib/Transition";
-import Announcement from "./Announcement";
```
Comment (infomiho) [inline web/src/components/Nav/index.jsx:5]: Formatting

File: web/docusaurus.config.ts [hunk 2]
```diff
@@ -32,7 +32,7 @@ const config: Config = {
     announcementBar: {
       id: "design-aithon",
       content:
-       '<b>Have a Wasp app in production?</b> 🐝 <a href="https://e44cy1h4s0q.typeform.com/to/EPJCwsMi">We\'ll send you some swag! 👕</a>',
+        '<b>Have a Wasp app in production?</b> 🐝 <a href="https://e44cy1h4s0q.typeform.com/to/EPJCwsMi">We\'ll send you some swag! 👕</a>',
```
Comment (infomiho) [inline web/docusaurus.config.ts:35]: Formatting

**Review by cprecioso — APPROVED** [review]
Good analysis, LGTM
