### PR TITLE
Optimistic Updates - No Fix for Flickering UI

### LINKED ISSUE #544: Have basic support for (react-query based) manual optimistic updates and cache invalidation
### Description

We want to support react-query style manual optimistic updates and cache invalidation in Wasp. 

This issue needs to be further refined.

### LINKED ISSUE #670: Solving Flickering UI During Optimistic Updates
## What do I mean by Flickering UI?
Many comments will discuss the flickering update problem. Here's the demo of it. You can find the explanation after the video.

https://user-images.githubusercontent.com/22752307/177961469-68e77b92-585f-40de-89d1-3f3d42faf4a8.mp4

### Explanation

1. The user sets a task to "Done."
4. The web app sends a request (`R1`) to the server, but it takes a long time to respond (let's say 3 seconds).
5. **The UI is optimistically updated** to show the task as "Done" while the server processes the request (i.e., before we receive a response).
6. The user now sees the task as "Done" and toggles it back to "Undone" (while the initial request is still being processed).
7. The client sends another request (`R2`) to the server, this time setting the status to "Undone". The server again takes a long time to respond.
8. The client receives the response to the original request (`R1`), but the server is still processing the second one (`R2`).
9. Receiving a response causes the client to invalidate the `operations/get-tasks` query and refetch it. This response arrives immediately.
10. The response lists the task as "Done" (since the server is still processing the second request), so the UI is updated to show the task as "Done."
11. The client finally receives the response to the second request (`R2`), which lists the task as "Undone" (i.e., the final state). The UI is updated one last time to show the task as "Undone."

## Is This a Big Deal?
Not really. The Internet (or the server) is rarely this slow. When it is, it is usually slow for everything. In other words, it's unlikely that the difference in response times between queries and actions is significant enough for the problem to manifest itself (but it is possible).

Also, users don't often behave this way (toggling between states much faster than the server can respond), so it's more of an edge case than a common occurrence.

Still, it is a problem, and it will happen from time to time.

## Potential Solutions
Before exploring the solutions, here's a PR that implements optimistic updates without solving the flickering problem #672 (base branch is `main`)

We've identified two distinct approaches to fixing the issue. Each approach has its pros and cons. Both of them bring additional complexity that might not be worth solving the problem in the first place. The two main questions are:
1. Should we attempt to fix flickering UI updates
2. If yes, which approach should we take?:
    1. #630 - Uses a counter to keep track of which queries we should postpone updating
    2. #668 - Allows all query invalidations and reapplies the optimistic update to all incoming responses
 
Both PRs extend and build on #672, whose branch (`filip-544-optimistic-updates-flicker`) is set as the base for comparison purposes. Feel free to change the base branch or make a new PR if you wish to compare the two approaches with each other directly.

### PR DESCRIPTION
**Pull request by sodic**
Fixes #544.

Does not fix #670.

### CODE REVIEW

File: waspc/data/Generator/templates/react-app/src/actions/index.js [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+
+
+function makeOptimisticUpdatesConfig(optimisticUpdatesConfig) {
+  return optimisticUpdatesConfig.map(({ getQuery, ...rest }) => ({
+    getQuery: (item) => parseQueryKey(getQuery(item)),
+    ...rest,
+  }))
+}
+
+function makeOptimisticUpdateOptions(queryClient, optimisticUpdatesConfig) {
```
Comment (sodic) [inline waspc/data/Generator/templates/react-app/src/actions/index.js:30]: This entire function is an implementation of [react-query's recommended approach for optimistic updates](https://react-query.tanstack.com/guides/optimistic-updates).

File: waspc/examples/todoApp/ext/Todo.js [hunk 2]
```diff
@@ -98,12 +99,25 @@ const Tasks = (props) => {
...
+    optimisticUpdates: [{
+      getQuery: () => [getTasks],
+      updateQuery: (updatedTask, oldTasks) => {
+        if (oldTasks === undefined) {
+          // cache is empty
+          return [updatedTask];
+        } else {
+          return oldTasks.map(task => task.id == updatedTask.id ? { ...task, ...updatedTask } : task)
+        }
+      }
```
Comment (sodic) [inline waspc/examples/todoApp/ext/Todo.js:112]: How should we behave when updating a query that does not yet exist in the cache?

Such a scenario can happen in the rare case when the users/developers wish to optimistically update something that is not in the current view. For example, in this case, the `oldData` will be `undefined`.

We can just document that the `updateQuery` should know how to handle the case when `oldTasks` is `undefined` (this is what I did here). Unfortunately, this approach does seem a bit janky (mainly because this behavior is something all queries could have in common).

Another option is ignoring such queries (i.e., not performing optimistic updates on queries not yet in the cache). This strategy would probably be OK in terms of UX (the query will get updated once the user lands on a view that features it, but it's less than ideal from the developer's perspective (a dev thinks they're updating something, and we're silently dropping it). We could mitigate the confusion by emphasizing that the `updateFn` _will not_ get called unless the provided query is already in the cache and optionally make this even more explicit by changing the function's name to something like `updateQueryIfCached`. That might be a bit extreme, though.

Comment (sodic) [reply waspc/examples/todoApp/ext/Todo.js:112]: Good idea. I'll go with it, seems like to most reasonable approach.

File: waspc/examples/todoApp/ext/pages/Task.js [hunk 3]
```diff
@@ -2,19 +2,44 @@ import React from 'react'
...
+    ]
+  })
+
   if (!task) return <div>Task with id {taskId} does not exist.</div>
   if (error) return <div>Error occurred! {error}</div>
 
   async function toggleIsDone() {
     try {
-      updateTaskIsDone({ id: task.id, isDone: !task.isDone })
+      updateTaskIsDoneAction.mutateAsync({ id: task.id, isDone: !task.isDone })
```
[the remark this answers is not in the document]
Comment (sodic) [reply waspc/examples/todoApp/ext/pages/Task.js:42]: @shayneczyzewski said:

----
I am glad you called this out. I don't have a great answer but was taken aback by the function named and assumed we were just using what was already there (but I'm not a React Query guru). I don't think we use the term "mutate" anywhere in user-facing docs, do we? If they are familiar with the API, they will probably grok it, but my eyes did notice that as "something new in Wasp" pretty quickly too.

[the remark this answers is not in the document]
Comment (sodic) [reply waspc/examples/todoApp/ext/pages/Task.js:42]: Yes, I've discussed this with @Martinsos on several occasions. I think the correct approach at this point would be renaming/redocumenting everything in terms of "action".

It is a bit unfortunate that React Query uses the term mutation for the same purpose, but iiwii (I think action is more appropriate anyway).

File: waspc/examples/todoApp/ext/pages/Task.js [hunk 4]
```diff
@@ -2,19 +2,44 @@ import React from 'react'
...
 
+  const updateTaskIsDoneAction = useAction(updateTaskIsDone, {
+    optimisticUpdates: [
+      {
+        getQuery: () => [getTask, { id: taskId }],
+        // This query's cache should should never be emtpy
+        updateQuery: ({ isDone }, oldTask) => ({ ...oldTask, isDone }),
+      },
+      {
+        getQuery: () => [getTasks],
```
[the remark this answers is not in the document]
Comment (sodic) [reply waspc/examples/todoApp/ext/pages/Task.js:22]: @shayneczyzewski said:

----
That may be a nice ergonomic enhancement for users, but yeah I agree it just makes the library code littered with checking types/shapes. But prob something we eventually want to consider.

File: waspc/examples/todoApp/ext/actions.js [hunk 5]
```diff
@@ -25,6 +27,7 @@ export const updateTaskIsDone = async ({ id, isDone }, context) => {
     throw new HttpError(403)
   }
 
+  await sleep(3000);
```
Comment (sodic) [inline waspc/examples/todoApp/ext/actions.js:30]: Added these sleeps in for demonstration purposes. Will remove if we ever merge this.

File: waspc/data/Generator/templates/react-app/src/actions/index.js [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+export { configureQueryClient } from '../queryClient'
+
+export function useAction(actionFn, actionOptions) {
+  const queryClient = useQueryClient();
+
+  // TODO(filip): Do we allow all react query options or should we consider a list of allowed options?
+  let options = {}
+
+  if (actionOptions?.optimisticUpdates) {
+    const optimisticUpdatesConfig = makeOptimisticUpdatesConfig(actionOptions.optimisticUpdates)
```
Comment (sodic) [inline waspc/data/Generator/templates/react-app/src/actions/index.js:15]: We have two optimistic update config "types":
- The public config is the what we document and what our users use
- The internal config is what we use internally (and this is where we remap it)

Currently, the only difference between the two is that the users are allowed to say:
```javascript
getQuery: () => [getTasks.queryCacheKey, taskId]
```
but also:
```javascript
getQuery: () => [getTasks, taskId] // notice the lack of queryCacheKey
```
Our internal config always expects a list of keys, so we have to parse it with the `parseQueryKey` function.

It might make sense to drop the support for one of those definition options (probably the one that requires users explicitly listing `queryCacheKey`, since we're doing our best to abstract it away).

Comment (sodic) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:15]: @shayneczyzewski said (and I did it, we now only allow functions and still need the mapper):

----

I agree it may make sense just to pick one to support.

File: waspc/data/Generator/templates/react-app/src/actions/index.js [hunk 7]
```diff
@@ -0,0 +1,74 @@
...
+
+    return previousData
+  }
+
+  function onError(err, item, context) {
+    context.previousData.forEach(async (data, queryKey) => {
+      await queryClient.cancelQueries(queryKey)
+      queryClient.setQueryData(queryKey, data)
+    })
+  }
```
Comment (sodic) [inline waspc/data/Generator/templates/react-app/src/actions/index.js:63]: TODO (filip): test this, couldn't get it to make sense. What errors is it supposed to catch? It triggers if I throw an exception inside onMutate and then complains that context.previousData is `undefined`.

Comment (sodic) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:63]: @shayneczyzewski said:

----

That does raise a good question, how do errors play a role in the counter approach? Are they automatically caught and then it just decrements it still?

File: waspc/examples/todoApp/ext/Todo.js [hunk 8]
```diff
@@ -98,12 +99,25 @@ const Tasks = (props) => {
 }
 
 const Task = (props) => {
+  const action = useAction(updateTaskIsDone, {
+    optimisticUpdates: [{
+      getQuery: () => [getTasks],
+      updateQuery: (updatedTask, oldTasks) => {
```
[the remark this answers is not in the document]
Comment (sodic) [reply waspc/examples/todoApp/ext/Todo.js:105]: @shayneczyzewski said:

----

Interesting. The only other thing I can think of is if we exposed some way for them to register a callback so when all the in-progress calls for some cache key are done and the queries were invalidated, that they can run something. So they would disable the delete button perhaps, run the optimistic update, and then when they knew the server was all caught up they can run a callback to re-enable?

File: waspc/data/Generator/templates/react-app/src/actions/index.js [hunk 9]
```diff
@@ -0,0 +1,74 @@
...
+  useQueryClient,
+} from 'react-query'
+
+export { configureQueryClient } from '../queryClient'
+
+export function useAction(actionFn, actionOptions) {
+  const queryClient = useQueryClient();
+
+  // TODO(filip): Do we allow all react query options or should we consider a list of allowed options?
+  let options = {}
```
Comment (Martinsos) [inline waspc/data/Generator/templates/react-app/src/actions/index.js:12]: What are the pros/cons?
Also, from what I see, right now we allow only `.optimisticUpdates`, right?

File: waspc/data/Generator/templates/react-app/src/actions/index.js [hunk 10]
```diff
@@ -0,0 +1,74 @@
...
+
+  if (actionOptions?.optimisticUpdates) {
+    const optimisticUpdatesConfig = makeOptimisticUpdatesConfig(actionOptions.optimisticUpdates)
+    options = makeOptimisticUpdateOptions(queryClient, optimisticUpdatesConfig)
+  }
```
Comment (Martinsos) [inline waspc/data/Generator/templates/react-app/src/actions/index.js:17]: You could make this a bit more immutable/functional like this:

```js
const options = actionOptions?.optimisticUpdates
  ? makeOptimisticUpdateOptions(
      queryClient,  
      makeOptimisticUpdatesConfig(actionOptions.optimisticUpdates)
    )
  : {} 
```

File: waspc/data/Generator/templates/react-app/src/actions/index.js [hunk 11]
```diff
@@ -0,0 +1,74 @@
...
+  return useMutation(actionFn, options)
+}
+
+
+function makeOptimisticUpdatesConfig(optimisticUpdatesConfig) {
+  return optimisticUpdatesConfig.map(({ getQuery, ...rest }) => ({
+    getQuery: (item) => parseQueryKey(getQuery(item)),
+    ...rest,
+  }))
+}
```
Comment (Martinsos) [inline waspc/data/Generator/templates/react-app/src/actions/index.js:28]: So you basically take already existing config and modify it so that getQuery works a bit differently. I am guessing that is so because we want to have a bit different interface compared to what react-query does? So what this function is really doing is transforming our optimisticUpdatesConfig into react query's optimisticUpdatesConfig?
If so, we could name it that way:
```js
makeRqOptimisticUpdatesConfig(waspOptimisticUpdatesConfig) {
  ...
}
```

File: waspc/data/Generator/templates/react-app/src/actions/index.js (hunk 10 above)
Comment (Martinsos) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:17]: I would also consider renaming them to `mutationOptions`.

File: waspc/data/Generator/templates/react-app/src/actions/index.js (hunk 11 above)
Comment (Martinsos) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:28]: This function could also maybe benefit from a bit of comments to explain what it takes and what it returns, since we don't have any types.

File: waspc/data/Generator/templates/react-app/src/actions/index.js (hunk 1 above)
Comment (Martinsos) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:30]: We could mention that in the comments of the function.

File: waspc/data/Generator/templates/react-app/src/actions/index.js [hunk 12]
```diff
@@ -0,0 +1,74 @@
...
+  return {
+    onMutate,
+    onError,
+  }
+}
+
+function parseQueryKey(queryKey) {
+  const [queryFn, ...otherKeys] = queryKey
+  return [queryFn.queryCacheKey, ...otherKeys]
+}
```
Comment (Martinsos) [inline waspc/data/Generator/templates/react-app/src/actions/index.js:74]: Could you write a comment explaining what this functions does?

File: waspc/data/Generator/templates/react-app/src/actions/index.js [hunk 13]
```diff
@@ -0,0 +1,74 @@
...
+    ...rest,
+  }))
+}
+
+function makeOptimisticUpdateOptions(queryClient, optimisticUpdatesConfig) {
+  async function onMutate(item) {
+    const queriesToUpdate = optimisticUpdatesConfig.map(({ getQuery, ...rest }) => ({
+      queryKey: getQuery(item),
+      ...rest,
+    }))
```
Comment (Martinsos) [inline waspc/data/Generator/templates/react-app/src/actions/index.js:35]: You say queriesToUpdate, but you return { queryKey, ... rest }. That doesn't look like query? I think I am missing a ton of context here, but maybe you could alleviate that with some comments?

File: waspc/data/Generator/templates/react-app/src/actions/index.js (hunk 1 above)
Comment (Martinsos) [inline waspc/data/Generator/templates/react-app/src/actions/index.js:30]: Could you pls comment this whole function, both regarding external API (what it takes / does / returns) and regarding its internal steps?
I have to admit that I am finding JS very hard to read and understand since there are no types + the stuff we are doing here is relatively complex so I am missing a lot of context -> if you could provide some of it via comments, that would help me a lot in understanding this code.

File: waspc/examples/todoApp/ext/Todo.js [hunk 14]
```diff
@@ -98,12 +99,25 @@ const Tasks = (props) => {
 }
 
 const Task = (props) => {
+  const action = useAction(updateTaskIsDone, {
+    optimisticUpdates: [{
+      getQuery: () => [getTasks],
```
Comment (Martinsos) [inline waspc/examples/todoApp/ext/Todo.js:104]: Is this an API that we define, or is it react query thing? What does getQuery stand for?

File: waspc/examples/todoApp/ext/Todo.js (hunk 2 above)
Comment (Martinsos) [reply waspc/examples/todoApp/ext/Todo.js:112]: Or, we could be explicit about two cases existing, by allowing them to define `updateCachedQuery` and/or `updateEmptyQuery`. So if they don't define the second one, we do default behaviour.

File: waspc/examples/todoApp/ext/Todo.js [hunk 15]
```diff
@@ -98,12 +99,25 @@ const Tasks = (props) => {
 }
 
 const Task = (props) => {
+  const action = useAction(updateTaskIsDone, {
```
Comment (Martinsos) [inline waspc/examples/todoApp/ext/Todo.js:102]:
```suggestion
  const { mutateAsync: updateTaskIsDoneOptimistically } = useAction(updateTaskIsDone, {
```

File: waspc/examples/todoApp/ext/pages/Task.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (Martinsos) [reply waspc/examples/todoApp/ext/pages/Task.js:22]: Agree with you all! I am ok with anything for now and we can adapt in the future.
Maybe let's keep it simple for now.

File: waspc/examples/todoApp/ext/pages/Task.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (Martinsos) [reply waspc/examples/todoApp/ext/pages/Task.js:42]: Ah yes this is tricky.
I am not sure what to do! What are our options?
1. We have a mix of action and mutate terms -> action coming from Wasp, mutate coming from react query.
2. We rename all "mutate"s in react query API to be "action". But that sounds pretty dirty to me and people will have hard time looking up react query's docs. We could rewrite their docs like blitz does but I am not sure it is worth investing such effort, I like much better just pointing them to existing docs.
3. We drop term "action" in Wasp and call it "mutation". I think "action" is more correct term but what can we do. This is a lot of changes but it will work ok once we do it. Although I will always be slightly unhappy that it is called mutation and not action :D.

Is there any other option that I didn't mention? What do you think?
@sodic you said 
> I think the correct approach at this point would be renaming/redocumenting everything in terms of "action".

Does that mean doing option 2 or option 3?

**Review by Martinsos — COMMENTED** [review]
Super cool! Not a lot of code actually, to introduce optimistic updates.
I left some comments, while for some better comments I am missing a bit of context -> but if you comment the code a bit more I think that should give me enough push to understand it all.
We should assume that somebody who doesn't know a lot about the whole optimistic updates business is reading the code and we want them to be able to find their way around at least with some success.

**Comment by Martinsos** [comment]
Regarding the documentaion -> you are leaving that for the end?

File: waspc/data/Generator/templates/react-app/src/actions/index.js (hunk 10 above)
Comment (sodic) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:17]: In the sole context of this PR: yes, it makes the code nicer.

However, both PRs/approaches that the flickering problem assign an additional thing inside the if block (a modified `mutationFn`). In those cases, we'd need either:
- Two identical ternary operators and two separate calls to `makeOptimisticUpdatesConfig` for two assignments
- Three identical ternary operators for three assignments and no way to communicate that they're mutually dependent (which would be a problem if we had types)

So, in both PRs that build on this one, the cleaner approach is using an `if` statement. I decided to leave the `if` statement in this (base) PR as well. It avoids cluttering the diff with irrelevant/cosmetic changes and keeps the spotlight on the changes required to solve the flickering UI problem.

File: waspc/data/Generator/templates/react-app/src/actions/index.js (hunk 11 above)
Comment (sodic) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:28]: I agree with both comments (will rename the function and add explanations).

File: waspc/data/Generator/templates/react-app/src/actions/index.js (hunk 1 above)
Comment (sodic) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:30]: We definitely could, yes :)

Comment (sodic) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:30]: Definitely, will do.

File: waspc/data/Generator/templates/react-app/src/actions/index.js (hunk 13 above)
Comment (sodic) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:35]: Yes, I got a bit liberal with the word `query` here. The object contains everything we need to perform an optimistic update. I'll do an additional pass that takes care of the naming and code style before requesting a final review.

File: waspc/examples/todoApp/ext/Todo.js (hunk 14 above)
Comment (sodic) [reply waspc/examples/todoApp/ext/Todo.js:104]: It's an API we define.

#### The Jist
Ideally, it would only be `query` and we'd provide it with `[getTasks]`<sup>1</sup>.
Unfortunately, optimistic updates often require local lexical context for identifying the query (e.g., when updating a task with a specific ID). To support this, we need to have closures in the query-identifier array, and for that we need a function. To make it clear that we expect a function that returns a query (instead of directly expecting a query), we call the field `getQuery`.

#### The Long Story
A richer API could look something like this:
```javascript
const taskId = // we have access to the optimistically updated task ID here.
optimisticUpdates: [{
    query: [getTasks],
    // ...
  },
  {
    getQuery: () => [getTask, taskId],
    // ...
  }
]
```
Or we could have gone the usual javascript/python route and just treated the field differently depending on its type:
```javascript
const taskId = // we have access to the optimistically updated task ID here.
optimisticUpdates: [{
    query: [getTasks],
    // ...
  },
  {
    query: () => [getTasks, taskId],
    // ...
  }
]
```
I wasn't a fan of either approach, so I decided to limit the public API to only accept functions (as they're expressive enough to cover all use cases). And, since we're now only accepting functions, `getQuery` seemed like a more appropriate name:
```javascript
const taskId = // we have access to the optimistically updated task ID here.
optimisticUpdates: [{
    getQuery: () => [getTasks],
    // ...
  },
  {
    getQuery: () => [getTasks, taskId],
    // ...
  }
]
```
#### How's Any of This a "Query" anyway?
Finally, the last point of confusion probably comes from the implication that the array `[getTasks, taskId]` is a "query", which is different from all other parts of Wasp (where we consider the word "query" to mean a function). So, yes, I should probably rename that :)

React query calls a similar array a "query key", but that doesn't feel quite right. Their query key is `[queryCacheKey : string, ...otherStuff]`, while ours is `[queryFn: function, ...otherStuff]` (we decided to keep hiding the `queryCacheKey`, more on that [here](https://github.com/wasp-lang/wasp/pull/672#discussion_r923520647)). Calling them the same might cause confusion. Any ideas on how to approach this?

[1]  Technically, it would probably only be `getTasks` (without the array), but that's a [different story](https://github.com/wasp-lang/wasp/pull/672#discussion_r923518439). I'll assume we settled on always using the array.

File: waspc/examples/todoApp/ext/Todo.js (hunk 2 above)
Comment (sodic) [reply waspc/examples/todoApp/ext/Todo.js:112]: But then they would often have to use the same function twice, right?

File: waspc/examples/todoApp/ext/pages/Task.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (sodic) [reply waspc/examples/todoApp/ext/pages/Task.js:42]: It was option 2, but now I don't like it anymore :upside_down_face: 

There is a third option, though. I could try to implement optimistic updates without using React Query. From what I've seen so far, it should be fairly straightforward. We would be losing the benefits of `useAction` though, but it would also reduce complecity.

**Comment by sodic** [comment]
> Regarding the documentaion -> you are leaving that for the end?

Yes, I'll take care of it once the API becomes "stable".

File: waspc/data/Generator/templates/react-app/src/actions/index.js (hunk 9 above)
Comment (sodic) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:12]: That's true, yes. I've experimented with merging objects, but we don't provide any configuration options at the moment.

Comment (sodic) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:12]: Pros/cons:
- Having more options
- Matching React Query's API 1 on 1 (easier to document, although we'd still have to cover the edge cases)
- Risking conflicts when users try to implement optimistic updates themselves

Versus (what if we don't support all react query options):
- Having a cleaner API (not introducing something we might not need or something users might use in ways we didn't expect and cause us problems)
- Having to put more effort into the docs (instead of just delegating it to React Query)
- More control

I'm leaning towards the second option

File: waspc/examples/todoApp/ext/Todo.js (hunk 2 above)
Comment (Martinsos) [reply waspc/examples/todoApp/ext/Todo.js:112]: Why the same function? I guess they would provide two different JS functions?

File: waspc/examples/todoApp/ext/pages/Task.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (Martinsos) [reply waspc/examples/todoApp/ext/pages/Task.js:42]: Uff that sounds like can of worms we might not want to do right now? It might get complicated + we need to write docs then.
So we have 4 options now. What do you think about each of them?

File: waspc/data/Generator/templates/react-app/src/actions/index.js (hunk 9 above)
Comment (Martinsos) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:12]: I generally like leaning on external libraries for now, since we are yet early and have a lot of stuff on our plate to handle anyway. So if we can delegate and avoid writing and maintaining our docs, I vote for that. But if you feel that it is not worth it compared to control / safety we get, then let's go for the second one. You are the best judge here, I would just nudge you to imagine the practical use cases and pick the best option based on that.

File: waspc/examples/todoApp/ext/Todo.js (hunk 14 above)
Comment (Martinsos) [reply waspc/examples/todoApp/ext/Todo.js:104]: Ok all makes sense!
Regarding name -> well, probably best to do the usual practice of trying to explain it to somebody. So how would you explain to me, in sentence or couple of them, what is this thing, if not `query`? And then let's keep reducing that until we get an identifier/name that we can use.

**Comment by Martinsos** [comment]
@sodic left some more comments on your comments, will wait for your next round of changes!

File: waspc/examples/todoApp/ext/Todo.js (hunk 14 above)
Comment (sodic) [reply waspc/examples/todoApp/ext/Todo.js:104]: I'd call it a `querySpecifier`.

Comment (Martinsos) [reply waspc/examples/todoApp/ext/Todo.js:104]: Ha ok, specifier is very generic though :D. But it does make some sense and I don't really have a better idea

File: waspc/examples/todoApp/ext/Todo.js (hunk 2 above)
Comment (sodic) [reply waspc/examples/todoApp/ext/Todo.js:112]: In cases where the logic is the same (which could be common).

File: waspc/data/Generator/templates/react-app/src/actions/index.js (hunk 12 above)
Comment (sodic) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:74]: I'll change the names and restructure the code so the comment might not be necessary.

File: waspc/examples/todoApp/ext/Todo.js (hunk 2 above)
Comment (Martinsos) [reply waspc/examples/todoApp/ext/Todo.js:112]: Aha! Ok, well I think you have a better idea of how often that might be. Ok, whatever you think makes most sense!

File: waspc/data/Generator/templates/react-app/src/actions/index.js (hunk 12 above)
Comment (Martinsos) [reply waspc/data/Generator/templates/react-app/src/actions/index.js]: Sounds great!

File: waspc/examples/todoApp/ext/pages/Task.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (sodic) [reply waspc/examples/todoApp/ext/pages/Task.js:42]: Ok, I took a fifth option. I restricted the API and "covered up" React Query. This means we won't be offering the additional benefits of their hooks, but our API and naming is more consistent. You can check the code for details.

File: waspc/examples/todoApp/ext/Todo.js (hunk 2 above)
Comment (sodic) [reply waspc/examples/todoApp/ext/Todo.js:112]: I'll leave it like this for now (let the programmers handle the case themselves). We can revise it at a later stage.

File: waspc/data/Generator/templates/react-app/src/actions/index.js (hunk 9 above)
Comment (sodic) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:12]: I ended up exposing our hook without the extra React Query stuff for now. They'll still be able to use React Query directly if they want it.

File: waspc/examples/todoApp/ext/Todo.js (hunk 14 above)
Comment (sodic) [reply waspc/examples/todoApp/ext/Todo.js]: Couldn't come up with anything better so I left it at specifier.

File: waspc/examples/todoApp/ext/Todo.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (sodic) [reply waspc/examples/todoApp/ext/Todo.js:105]: We decided it makes sense to let the programmer worry about this (i.e., no magic from our side) for now.

File: waspc/data/Generator/templates/react-app/src/actions/index.js (hunk 7 above)
Comment (sodic) [reply waspc/data/Generator/templates/react-app/src/actions/index.js]: We've since abandoned the counter approach, so luckily no need to answer that :sweat_smile: (but yes, it would cause problems).

As for my comments, I found and fixed the issue, it was an error on my side.

File: waspc/data/Generator/templates/react-app/src/actions/index.js [hunk 16]
```diff
@@ -0,0 +1,152 @@
...
+  const definitionErrors = []
+  if (typeof getQuerySpecifier !== 'function') {
+    definitionErrors.push('`getQuerySpecifier` is not a function.')
+  }
+  if (typeof updateQuery !== 'function') {
+    definitionErrors.push('`updateQuery` is not a function.')
+  }
+  if (definitionErrors.length) {
+    throw new TypeError(`Invalid optimistic update definition: ${definitionErrors.join(', ')}.`)
+  }
```
Comment (sodic) [inline waspc/data/Generator/templates/react-app/src/actions/index.js:51]: I'm still not sure how to handle these things in our API (by these things I mean runtime type checks for the stuff users pass into our functions). Should we just pretend we're getting the right values all the time and let the system break by itself? Should we fail on the first error we find, or collect as much as possible before throwing an exception.

Seems like our codebase takes several different approaches to this issue.

Comment (shayneczyzewski) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:51]: Yeah, good question. I think what you are doing, validating our expectations and then showing appropriate errors, makes sense here. I think I did something similar for the Google config function return object shape.

If it is something like a user-defined function that just explodes, and we have no recourse, I have just usually let them explode so they get contextual stack traces. But thinking more about it holistically does make sense.

Our future change to TS should help with these types of checks though, right?

File: waspc/data/Generator/templates/react-app/src/actions/index.js [hunk 17]
```diff
@@ -0,0 +1,227 @@
...
+      }
+
+      // Remember the snapshotted value to restore in case of an error.
+      previousData.set(queryKey, previousDataForQuery)
+    })
+
+    return { previousData }
+  }
+
+  function onError(err, item, context) {
```
Comment (shayneczyzewski) [inline waspc/data/Generator/templates/react-app/src/actions/index.js:180]: Super small, but you could add underscore to `err` and `item` due to not being used.

File: web/docs/language/features.md [hunk 18]
```diff
@@ -383,7 +392,8 @@ The object `context.entities.Task` exposes `prisma.task` from [Prisma's CRUD API
 
 Actions are very similar to Queries. So similar, in fact, we will only list the differences:
 1. They can (and most often should) modify the server's state, while Queries are only allowed to read it.
-2. Since Actions don't need to be reactive, Wasp doesn't provide a React hook for them (like `useQuery` for Queries) - you just call them directly.
+2. Actions don't need to be reactive so you can call them directly. Still, Wasp does provide a `useAction` React hook for adding extra behavior to the Action (e.g., optimistic updates).
+Read more about the [`useAction` hook](#the-useaction-hook) below
```
Comment (shayneczyzewski) [inline web/docs/language/features.md:396]: May want a period at the end of the line.

**Review by shayneczyzewski — COMMENTED** [review]
Great job @sodic Did one more brief pass and only found 2 super small things. I will let Martin wrap up his "dev reading docs" review, but great job!

File: waspc/data/Generator/templates/react-app/src/actions/index.js (hunk 17 above)
Comment (sodic) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:180]: Ah yes, I wanted to but forgot. Thanks!

File: web/docs/language/features.md [hunk 19]
```diff
@@ -412,8 +422,113 @@ import sayHi from '@wasp/actions/sayHi'
...
+Wasp's optimistic update API is deliberately small and focuses exclusively on updating Query caches (as that's the most common use case). You might need an API that offers more options or a higher level of control. If that's the case, instead of using Wasp's `useAction` hook, you can use _react-query_'s `useMutation` hook and directly work with [their low-level API](https://tanstack.com/query/v4/docs/guides/optimistic-updates?from=reactQueryV3&original=https://react-query-v3.tanstack.com/guides/optimistic-updates).
+
+If you decide to use _react-query_'s API directly, you will need access to the Query's cache key. Wasp internally uses this key but abstracts it from the programmer. Still, you can easily obtain it by accessing the `queryCacheKey` property on a Query:
+```js
+import { fetchTasks } from '@wasp/queries'
+
+const queryKey = fetchTasks.queryCacheKey
+```
 
 ### Cache Invalidation
```
Comment (Martinsos) [inline web/docs/language/features.md:533]: Is there anything we might want to update in this section? Maybe mention optimistic updates in some context? You will know better, just asking.

File: web/docs/language/features.md [hunk 20]
```diff
@@ -412,8 +422,113 @@ import sayHi from '@wasp/actions/sayHi'
...
+```
+
+#### The `useAction` hook
+When using Actions in components, you can enhance them with the help of the `useAction` hook. This hook comes bundled with Wasp and decorates Wasp Actions.
+In other words, the hook returns a function whose API matches the original Action while also doing something extra under the hood (depending on how you configure it).
+
+The `useAction` hook accepts two arguments:
+- `actionFn` (required) - The Wasp Action (i.e., the client-side query function generated by Wasp based on a query declaration) you wish to enhance.
+- `actionOptions` (optional) - An object configuring the extra features you want to add to the given Action. While this argument is technically optional, there is no point in using the `useAction` hook without providing it (it would be the same as using the Action directly). The Action options object supports the following fields: 
+  - `optimisticUpdates` (optional) - An array of objects where each object defines an optimistic update to perform on the query cache. To define an optimistic update, you must specify the following properties:
```
Comment (Martinsos) [inline web/docs/language/features.md:476]: If one doesn't know what an optimistic update is, this might be a bit hard to read. I wonder if we should have a section in docs called `Optimistic updates` and then there we elaborate further into this stuff?
For example, here we could just mention that you can provide optimisticUpdates option, but then refer you to `Optimistic updates` section for more details. And then in that section we could have a bit of a story -> what are optimistic updates, when to use them, how they are done in Wasp, examples, ... .

We don't have to do that in this PR though, we could do it in another PR, but I feel like that would help with understanding how and when to use this, as currently, it seems fairly complex to me.

**Review by Martinsos — APPROVED** [review]
@sodic left couple of comments but nothing major, and approved!
Pls take care of those as you wish and then feel free to merge!

File: waspc/data/Generator/templates/react-app/src/actions/index.js [hunk 21]
```diff
@@ -0,0 +1,152 @@
+import {
+  useMutation,
+  useQueryClient,
+} from 'react-query'
+
+export { configureQueryClient } from '../queryClient'
+
+/**
+ * A hook for adding extra behavior to a Wasp Action (e.g., optimistic updates).
```
[the remark this answers is not in the document]
Comment (sodic) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:84]: Haha, yes, that's exactly it - an implementation detail. Do you think it's fine if I don't mention anything about the reasoning in the docs? We could probably do away with using react-query for optimistic updates, but I left it in for now (as we'll probably want to use more features).

File: waspc/data/Generator/templates/react-app/src/actions/index.js [hunk 22]
```diff
@@ -0,0 +1,152 @@
...
+/**
+ * This function implements the methods necessary for configuring optimistic
+ * updates using React Query, as described by their documentation:
+ * https://tanstack.com/query/v4/docs/guides/optimistic-updates?from=reactQueryV3&original=https://react-query-v3.tanstack.com/guides/optimistic-updates
+ *
+ * @param {Object} queryClient The QueryClient instance used by React Query.
+ * @param {Object} optimisticUpdateDefinitions A list containing internal optimistic updates definition objects
+ * (i.e., a list where each object carries the instructions for performing particular optimistic update).
+ * @returns {Object} An object containing 'onMutate' and 'onError' functions corresponding to the given optimistic update
+ * definitions (check React Query's docs for details).
```
[the remark this answers is not in the document]
Comment (sodic) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:143]: It's three lines up, I'll clarify where to look.

File: waspc/data/Generator/templates/react-app/src/actions/index.js [hunk 23]
```diff
@@ -0,0 +1,152 @@
...
+  }
+}
+
+/**
+ * This function implements the methods necessary for configuring optimistic
+ * updates using React Query, as described by their documentation:
+ * https://tanstack.com/query/v4/docs/guides/optimistic-updates?from=reactQueryV3&original=https://react-query-v3.tanstack.com/guides/optimistic-updates
+ *
+ * @param {Object} queryClient The QueryClient instance used by React Query.
+ * @param {Object} optimisticUpdateDefinitions A list containing internal optimistic updates definition objects
```
[the remark this answers is not in the document]
Comment (sodic) [reply waspc/data/Generator/templates/react-app/src/actions/index.js]: Fixed, resolving

File: waspc/data/Generator/templates/react-app/src/actions/index.js [hunk 24]
```diff
@@ -0,0 +1,152 @@
...
+
+  let options = {}
+  if (actionOptions?.optimisticUpdates) {
+    const optimisticUpdateDefinitions = actionOptions.optimisticUpdates.map(translateToInternalDefinition)
+    options = makeRqOptimisticUpdateOptions(queryClient, optimisticUpdateDefinitions)
+  }
+
+  // NOTE: We decided to hide React Query's extra mutation features (e.g.,
+  // isLoading, onSuccess and onError callbacks, synchronous mutate) and only
+  // expose a simple async function whose API matches the original Action.
```
[the remark this answers is not in the document]
Comment (sodic) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:101]: Point taken, I'll add the reasoning :)

File: waspc/data/Generator/templates/react-app/src/actions/index.js [hunk 25]
```diff
@@ -0,0 +1,152 @@
...
+  }
+
+  return {
+    getQueryKey: (item) => getRqQueryKeyFromSpecifier(getQuerySpecifier(item)),
+    updateQuery,
+  }
+}
+
+/**
+ * This function implements the methods necessary for configuring optimistic
```
[the remark this answers is not in the document]
Comment (sodic) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:135]: This is much better, I'll use it. Thanks!

File: web/docs/language/features.md (hunk 19 above)
Comment (sodic) [reply web/docs/language/features.md:533]: Definitely, forgot about this part. I'll add it in.

File: web/docs/language/features.md (hunk 20 above)
Comment (sodic) [reply web/docs/language/features.md:476]: I agree and thought about it, maybe writing such a section could pass as a good first issue? If no one takes it up, I can do it myself.

File: waspc/data/Generator/templates/react-app/src/actions/index.js (hunk 21 above)
[the remark this answers is not in the document]
Comment (Martinsos) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:84]: I am ok with everything here!

File: waspc/data/Generator/templates/react-app/src/actions/index.js (hunk 22 above)
[the remark this answers is not in the document]
Comment (Martinsos) [reply waspc/data/Generator/templates/react-app/src/actions/index.js:143]: Oops never mind then, maybe I haven't seen that.

File: waspc/data/Generator/templates/react-app/src/actions/index.js (hunk 12 above)
Comment (sodic) [reply waspc/data/Generator/templates/react-app/src/actions/index.js]: Done
