### PR TITLE
Surface SendGrid errors from its response

### LINKED ISSUE #2266: Improve error reporting for email sender
Looking at the stack trace in this [Discord thread](https://discord.com/channels/686873244791210014/1280117478285905921/1280117478285905921) it's obvious we are not outputting the full error which is crucial for successful debugging. Also, we could maybe recognise common sets of errors and give extra info to the user like "it looks like you received a 403 error, did you set up the sending email properly?" and similar.

### PR DESCRIPTION
**Pull request by cprecioso**
### Description

Fixes #2266

When SendGrid throws an error, we will try to see if it has a `response.body.errors` property [(recommended by them)](https://github.com/sendgrid/sendgrid-nodejs/blob/main/docs/use-cases/success-failure-errors.md), and surface those errors through an `AggregateError`.

New console output:

```
[ Server ] POST /auth/email/signup 200 63.315 ms - 16
[ Server!] Failed to send email AggregateError: SendGrid error: Unauthorized
[ Server!]     at <anonymous> (/Users/carlos/Developer/Wasp/hello/.wasp/out/sdk/wasp/dist/server/email/core/providers/sendgrid.js:28:27)
[ Server!]     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
[ Server!]   [errors]: [
[ Server!]     {
[ Server!]       message: 'The provided authorization grant is invalid, expired, or revoked',
[ Server!]       field: null,
[ Server!]       help: null
[ Server!]     },
[ Server!]     ResponseError: Unauthorized
[ Server!]         at /Users/carlos/Developer/Wasp/hello/node_modules/@sendgrid/client/src/classes/client.js:146:29
[ Server!]         at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
[ Server!]       code: 401,
[ Server!]       response: [Object]
[ Server!]     }
[ Server!]   ]
[ Server!] }
```

<details>
<summary>Example previous output</summary>

```
[ Server!] Failed to send email ResponseError: Forbidden
[ Server!]     at /home/kaloyan/projects/podcast-FE/app/node_modules/@sendgrid/client/src/classes/client.js:146:29
[ Server!]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[ Server!]   code: 403,
[ Server!]   response: {
[ Server!]     headers: {
[ Server!]       server: 'nginx',
[ Server!]       date: 'Mon, 02 Sep 2024 10:41:16 GMT',
[ Server!]       'content-type': 'application/json',
[ Server!]       'content-length': '281',
[ Server!]       connection: 'keep-alive',
[ Server!]       'access-control-allow-origin': 'https://sendgrid.api-docs.io',
[ Server!]       'access-control-allow-methods': 'POST',
[ Server!]       'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
[ Server!]       'access-control-max-age': '600',
[ Server!]       'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html',
[ Server!]       'strict-transport-security': 'max-age=600; includeSubDomains'
[ Server!]     },
[ Server!]     body: { errors: [Array] }
[ Server!]   }
[ Server!] }
```

</details>

---

I also checked if Mailgun has further info we can surface but their errors seems quite obscure, I don't think there's anything I can take from here.

```
[ Server ] POST /auth/email/signup 200 62.387 ms - 16
[ Server!] Failed to send email [Error: Unauthorized] {
[ Server!]   status: 401,
[ Server!]   details: 'Forbidden',
[ Server!]   type: 'MailgunAPIError'
[ Server!] }
```

### Select what type of change this PR introduces:
1. [ ] **Just code/docs improvement** (no functional change).
2. [x] **Bug fix** (non-breaking change which fixes an issue).
3. [ ] **New feature** (non-breaking change which adds functionality).
4. [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected).

### CODE REVIEW

File: waspc/data/Generator/templates/sdk/wasp/server/email/core/providers/sendgrid.ts [hunk 1]
```diff
@@ -22,6 +22,22 @@ export function initSendGridEmailSender(
         subject: email.subject,
         text: email.text,
         html: email.html,
+      }).catch((error) => {
+        // SendGrid can return an array of errors in its response,
+        // but the client doesn't surface them appropiately.
```
Comment (Martinsos) [inline waspc/data/Generator/templates/sdk/wasp/server/email/core/providers/sendgrid.ts:27]:
```suggestion
        // but the client doesn't surface them appropriately.
```

File: waspc/data/Generator/templates/sdk/wasp/server/email/core/providers/sendgrid.ts [hunk 2]
```diff
@@ -22,6 +22,22 @@ export function initSendGridEmailSender(
...
+        // If we find it, we will throw an AggregateError with all the errors
+        // so that they are all printed. Otherwise, we will throw the
+        // original error.
+
+        const responseErrors = error?.response?.body?.errors;
+        if (responseErrors && Array.isArray(responseErrors)) {
+          throw new AggregateError(
```
Comment (Martinsos) [inline waspc/data/Generator/templates/sdk/wasp/server/email/core/providers/sendgrid.ts:34]: Cool I didn't know about AggregateError!

**Review by infomiho — APPROVED** [review]
Looking good, nice job
