### PR TITLE
Do not fail on `--help` argument

### LINKED ISSUE #3438: `wasp build start --help` says "Parsing failed" and returns non-zero exit code
When you run `wasp build start --help`, the command says that "Parsing arguments failed" and returns an exit code of `1`, but does mention `--help` as a valid argument.

We should not say "parsing failed" and give a `0` error code.

```
$ wasp build start --help


❌ --- [Error] Parsing arguments failed: ------------------------------------------

Usage: wasp build start [-c|--client-env NAME=VALUE] 
                        [--client-env-file FILE_PATH] 
                        [-s|--server-env NAME=VALUE] 
                        [--server-env-file FILE_PATH]

Available options:
  -c,--client-env NAME=VALUE
                           Set an environment variable for the client (can be
                           used multiple times)
  --client-env-file FILE_PATH
                           Load environment variables for the client from a file
                           (can be used multiple times)
  -s,--server-env NAME=VALUE
                           Set an environment variable for the server (can be
                           used multiple times)
  --server-env-file FILE_PATH
                           Load environment variables for the server from a file
                           (can be used multiple times)
  -h,--help                Show this help text
```

### PR DESCRIPTION
**Pull request by cprecioso**
- Fixes #3438

## Description

We are exiting the CLI with a failure when using the `--help` flags in Options.Applicative parsers.

This is because, in that case, the library return a `Failure` but with an `ExitCode.ExitSuccess` inside of it. We were not inspecting it, and just throwing an error even when it didn't need to be one.

Because we need to short-circuit the full execution, but without throwing an error; and `parseArguments` was being used in the exact same way in every caller; I transformed the `parseArguments` function into a `withArguments` one that wraps the `Command` and can decide whether to run it or not.

## Type of change

- [ ] **🔧 Just code/docs improvement** 
- [x] **🐞 Bug fix** 
- [ ] **🚀 New/improved feature** 
- [ ] **💥 Breaking change** 

## Checklist

- [x] I tested my change in a Wasp app to verify that it works as intended.

- 🧪 Tests and apps:

  > [!NOTE]
  > I didn't add any tests as we don't have testing at such high-level in the CLI itself, we'd end up testing `Options.Applicative` itself.

  - [ ] I added **unit tests** for my change. 
  - [ ] _(if you fixed a bug)_ I added a **regression test** for the bug I fixed. 
  - [ ] _(if you added/updated a feature)_ I added/updated **e2e tests** in `examples/kitchen-sink/e2e-tests`.
  - [ ] _(if you added/updated a feature)_ I updated the **starter templates** in `waspc/data/Cli/templates`, as needed.
  - [ ] _(if you added/updated a feature)_ I updated the **example apps** in `examples/`, as needed.
    - [ ] _(if you updated `examples/tutorials`)_ I updated the tutorial in the docs (and vice versa).

- 📜 Documentation:

  - [ ] _(if you added/updated a feature)_ I **added/updated the documentation** in `web/docs/`.

- 🆕 Changelog: _(if change is more than just code/docs improvement)_
  - [x] I updated `waspc/ChangeLog.md` with a **user-friendly** description of the change.
  - [ ] _(if you did a breaking change)_ I added a step to the current **migration guide** in `web/docs/migration-guides/`.
  - [x] I **bumped the `version`** in `waspc/waspc.cabal` to reflect the changes I introduced.

### CODE REVIEW

File: waspc/src/Wasp/Psl/Parser/Common.hs [hunk 1]
```diff
@@ -18,7 +18,6 @@ module Wasp.Psl.Parser.Common
   )
 where
 
-import Control.Applicative (liftA2)
```
Comment (cprecioso) [inline waspc/src/Wasp/Psl/Parser/Common.hs]: Compiler was giving me a warning

Comment (sodic) [reply waspc/src/Wasp/Psl/Parser/Common.hs]: Yeah, this is now in global scope.

File: waspc/cli/src/Wasp/Cli/Util/Parser.hs [hunk 2]
```diff
@@ -1,22 +1,47 @@
...
+withArguments cmdName parser onSuccess args =
+  dispatch $ parseArguments cmdName parser args
+  where
+    dispatch (Success result) = do
+      onSuccess result
+    dispatch (Failure _ helpMessage) = do
+      throwError $ CommandError "Parsing arguments failed" helpMessage
+    dispatch (Stop helpMessage) = do
+      cliSendMessageC $ Msg.Info helpMessage
+      return ()
```
Comment (sodic) [inline waspc/cli/src/Wasp/Cli/Util/Parser.hs]: Seems like we can simplify this:
```hs
withArguments :: String -> Opt.Parser a -> (a -> Command ()) -> Arguments -> Command ()
withArguments cmdName parser onSuccess args = case parseArguments cmdName parser args of
  (Success result) -> onSuccess result
  (Failure _ helpMessage) -> throwError $ CommandError "Parsing arguments failed" helpMessage
  (Stop helpMessage) -> cliSendMessageC $ Msg.Info helpMessage
```

File: waspc/cli/src/Wasp/Cli/Util/Parser.hs [hunk 3]
```diff
@@ -1,22 +1,47 @@
...
+
+data ArgsResult a
+  = Success a
+  | Failure Int String
+  | Stop String
```
Comment (sodic) [inline waspc/cli/src/Wasp/Cli/Util/Parser.hs]:
```hs
data ParsingResult a  -- or even 'args' instead of just a
  = ParsedArguments a
  | ParsingFailed Int String
  | HelpCalled String  -- or ShowHelp or HelpRequested, something along those lines
```
I think this is a little more informative. No need to copy it verbatim, just consider the general idea.

File: waspc/cli/src/Wasp/Cli/Util/Parser.hs [hunk 4]
```diff
@@ -1,22 +1,47 @@
...
+parserResultToArgsResult _ (Opt.Success success) = Success success
+parserResultToArgsResult cmdName (Opt.CompletionInvoked _) =
   error $ "Completion invoked when parsing '" <> cmdName <> "', but this should never happen"
-parserResultToEither cmdName (Opt.Failure failure) = Left $ show help
+parserResultToArgsResult cmdName (Opt.Failure failure) =
+  failureToArgsResult $ Opt.execFailure failure cmdName
   where
-    (help, _, _) = Opt.execFailure failure cmdName
+    failureToArgsResult (help, EC.ExitSuccess, _) = Stop $ show help
+    failureToArgsResult (help, EC.ExitFailure exitCodeInt, _) = Failure exitCodeInt $ show help
```
Comment (sodic) [inline waspc/cli/src/Wasp/Cli/Util/Parser.hs]: We can simplify this as well:
```hs
parserResultToArgsResult cmdName (Opt.Failure failure) =
  case Opt.execFailure failure cmdName of
    (help, EC.ExitSuccess, _) -> Stop $ show help
    (help, EC.ExitFailure exitCodeInt, _) -> Failure exitCodeInt $ show help
```

**Comment by cprecioso** [comment]
Ready

File: waspc/cli/src/Wasp/Cli/Util/Parser.hs [hunk 5]
```diff
@@ -1,22 +1,44 @@
...
+withArguments :: String -> Opt.Parser a -> (a -> Command ()) -> Arguments -> Command ()
+withArguments cmdName parser onSuccess args =
+  case parseArguments cmdName parser args of
+    (ArgsParsed result) -> do
+      onSuccess result
+    (ParseFailure helpMessage) -> do
+      throwError $ CommandError "Parsing arguments failed" helpMessage
+    (ShowHelp helpMessage) -> do
+      cliSendMessageC $ Msg.Info helpMessage
+      return ()
```
Comment (sodic) [inline waspc/cli/src/Wasp/Cli/Util/Parser.hs]: Why the `return ()`?

File: waspc/cli/src/Wasp/Cli/Util/Parser.hs [hunk 6]
```diff
@@ -1,22 +1,44 @@
...
-parseArguments :: String -> Opt.Parser a -> Arguments -> Either String a
-parseArguments cmdName parser args =
-  parserResultToEither cmdName $
-    Opt.execParserPure Opt.defaultPrefs parserInfo args
-  where
-    parserInfo = Opt.info (parser Opt.<**> Opt.helper) Opt.fullDesc
+withArguments :: String -> Opt.Parser a -> (a -> Command ()) -> Arguments -> Command ()
+withArguments cmdName parser onSuccess args =
+  case parseArguments cmdName parser args of
+    (ArgsParsed result) -> do
```
Comment (sodic) [inline waspc/cli/src/Wasp/Cli/Util/Parser.hs]: Why the `do`?

File: waspc/cli/src/Wasp/Cli/Util/Parser.hs [hunk 7]
```diff
@@ -1,22 +1,44 @@
...
+  case Opt.execParserPure Opt.defaultPrefs parserInfo args of
+    (Opt.Success success) -> ArgsParsed success
+    (Opt.CompletionInvoked _) ->
+      error $ "Completion invoked when parsing '" <> cmdName <> "', but this should never happen"
+    (Opt.Failure failure) ->
+      case Opt.execFailure failure cmdName of
+        (help, EC.ExitSuccess, _) ->
+          ShowHelp $ show help
+        (help, EC.ExitFailure _, _) ->
+          ParseFailure $ show help
```
Comment (sodic) [inline waspc/cli/src/Wasp/Cli/Util/Parser.hs]: I find cases more readable when on a single line. It makes the mappings look cleaner and more like mappings IMO. This applies to both the `withArguments` function and to the two cases here.

But do what you prefer. RAW.

File: waspc/cli/src/Wasp/Cli/Util/Parser.hs (hunk 5 above)
Comment (cprecioso) [reply waspc/cli/src/Wasp/Cli/Util/Parser.hs]: Just to make clear that we're not running anything else, but i can remove it

File: waspc/cli/src/Wasp/Cli/Util/Parser.hs (hunk 6 above)
Comment (cprecioso) [reply waspc/cli/src/Wasp/Cli/Util/Parser.hs]: for consistency, eveyrthing is `do`, but i can change it

File: waspc/cli/src/Wasp/Cli/Util/Parser.hs (hunk 7 above)
Comment (cprecioso) [reply waspc/cli/src/Wasp/Cli/Util/Parser.hs]: 👍
