### PR TITLE
Fix directly calling operations on the frontend 

### LINKED ISSUE #1923: Fix docs for directly calling Operations from the client
This example is missing a mention of passing the `queryCacheKey`: https://wasp-lang.dev/docs/data-model/operations/queries#using-queries.

This example is missing a cast necessary for accessing the `queryCacheKey` in TypeScript: https://wasp-lang.dev/docs/data-model/operations/queries#using-queries.

Decide on the following points and update the code/docs accordingly:
 - Do we want to extract the `queryCacheKey` when inside the Query and spare the user from having to pass it in themselves?
 - Do we want to document the existence of the `queryCacheKey` in the type we expose to the user (instead of hiding it like we do now)?

### PR DESCRIPTION
**Pull request by sodic**
Fixes #1923.

I'll do all the testing once this gets approved.
I've already tested it a couple of times and it all works, but I'll hold of the final just-in-case tests until all changes are final.

Tasks:
- [x] Fix query API.
- [ ] Figure out what to do with the type `Query`, `Action`, `Operation`, `QueryFor`, `OperationFor`. Should we expose some of them and remove duplication?
- [x] Test queries with no payload.
- [x] Test queries with payload.
- [x] Test optimistic updates on queries with no payload.
- [x] Test optimistic updates on queries with payload.
- [x] Test caching on queries with payload.
- [x] Test caching on queries without payload.
- [x] Fix query api types.
- [x] Test actions.
- [x] Test todoApp build.
- [x] Update docs.
- [ ] Test CRUD

### CODE REVIEW

File: waspc/data/Generator/templates/sdk/wasp/client/operations/queries/core.ts [hunk 1]
```diff
@@ -13,7 +13,9 @@ export function createQuery<BackendQuery extends GenericBackendQuery>(
 ): QueryFor<BackendQuery> {
   const queryRoute = makeOperationRoute(relativeQueryPath)
 
-  async function query(queryKey, queryArgs) {
+  async function query(queryArgs) {
+    // Assumes `addMetadataToQuery` added the `queryCacheKey` property to the query.
+    const queryKey = (query as any).queryCacheKey
```
Comment (sodic) [inline waspc/data/Generator/templates/sdk/wasp/client/operations/queries/core.ts:18]: Todo: fix the issue in `operations/core.ts#useQuery` where they call it with the cache key.

Test for queries that have a payload.

File: waspc/examples/todoApp/src/TestRpcTypes.ts
Comment (sodic) [inline waspc/examples/todoApp/src/TestRpcTypes.ts:1]: That's right. I've pulled a Miho.

File: waspc/data/Generator/templates/sdk/wasp/client/operations/actions/core.ts [hunk 2]
```diff
@@ -41,8 +41,9 @@ export function createAction<BackendAction extends GenericBackendAction>(
 }
 
 // PRIVATE API
-export type ActionFor<BackendAction extends GenericBackendAction> =
-  Action<Parameters<BackendAction>[0], _Awaited<_ReturnType<BackendAction>>>
-
+export type ActionFor<BackendQuery extends GenericBackendAction> =
+  Parameters<BackendQuery> extends []
```
Comment (sodic) [inline waspc/data/Generator/templates/sdk/wasp/client/operations/actions/core.ts:45]: Todo: comment on why this was necessary.

File: waspc/data/Generator/templates/sdk/wasp/client/operations/queries/core.ts [hunk 3]
```diff
@@ -1,53 +1,64 @@
...
-): void
-
-// PRIVATE API
-export function addMetadataToQuery(
-  query,
-  { relativeQueryPath, queryRoute, entitiesUsed }
-) {
-  query.queryCacheKey = [relativeQueryPath]
+// PRIVATE API (used in SDK)
+export function buildAndRegisterQuery<Input, Output>(
```
Comment (sodic) [inline waspc/data/Generator/templates/sdk/wasp/client/operations/queries/core.ts:39]: Having a proper function (i.e., a smart constructor) seemed cleaner than having a function with side effects that you might forget to call.

File: waspc/data/Generator/templates/sdk/wasp/client/operations/queries/core.ts [hunk 4]
```diff
@@ -1,53 +1,64 @@
...
+  queryFn: ClientOperation<Input, Output>,
+  { queryCacheKey, queryRoute, entitiesUsed }:
```
Comment (sodic) [inline waspc/data/Generator/templates/sdk/wasp/client/operations/queries/core.ts:41]: I took the creation of the `queryCacheKey` out to make it easily accessible in `createQuery`. The bonus is that this function now has fewer responsibilities.

File: waspc/data/Generator/templates/sdk/wasp/client/operations/rpc.ts [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+import type {
+  _Awaited,
+  _ReturnType,
+} from "wasp/universal/types"
+
+// PRIVATE API (but should maybe be public, users define values of this type)
+export type Query<Input, Output> = QueryFunction<Input, Output> & QueryMetadata
+
+// PRIVATE API (but should maybe be public, users define values of this type)
+export type Action<Input, Output> = ClientOperation<Input, Output>
```
Comment (sodic) [inline waspc/data/Generator/templates/sdk/wasp/client/operations/rpc.ts:11]: @infomiho What do you think? Should these types be added to our public API?

Won't do this now, but I can create an issue.

File: waspc/data/Generator/templates/sdk/wasp/client/operations/rpc.ts [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+
+// PRIVATE API
+export type QueryFunction<Input, Output> = ClientOperation<Input, Output>
+
+// PRIVATE API
+export type QueryMetadata = {
+  queryCacheKey: string[]
+  route: Route
+}
```
Comment (sodic) [inline waspc/data/Generator/templates/sdk/wasp/client/operations/rpc.ts:20]: I decided to expose both `route` and `queryCacheKey` to our users:
- `queryCacheKey` - Because they need it to unlock all the capabilities of tanstack-query (as our docs tell them)
- `route` - Because I didn't want to complicate things by introducing another "internal" type.

 Let me know if you think this is a problem

File: waspc/data/Generator/templates/sdk/wasp/client/operations/rpc.ts [hunk 7]
```diff
@@ -0,0 +1,38 @@
...
+
+// PRIVATE API (needed in SDK)
+export type OperationRpcFor<BackendOperation extends GenericBackendOperation> =
+  Parameters<BackendOperation> extends []
```
Comment (sodic) [inline waspc/data/Generator/templates/sdk/wasp/client/operations/rpc.ts:24]: A [playground link](https://www.typescriptlang.org/play/?noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&ts=4.9.5#code/PTAEBUAsEsGdTqAhqW0C2AHANtAZtAKYAmoAboQE5oD2AdqDXqAO6RIAurhoxNCDGgFdKoAMY1ihADSgARkI4AoEKkjDspQgA8cSaAw6QelQklj15hGHVJGeAAwAKSSknSEOVWAB4AQkhiANaEtgDymFSc0PQAfKA6XrbwANoAug4qYBK20BwxdAB0SlmgAILkNNCkEVH5llIEdCSseZCgDrDRsASEsA4JyaBCmMjwRogcAJ6RpQAUmJQ0kaJkVaR4QnRi9XQAlErTkaAAausAYltioAC8oHN7t-F0QuhyVCWqUIiTxqCLNDE2H0HlIsBGVCOPCYyGw2FAtTcu1gxR0mBolC4UNAAHFQlRoGIAsFQsREdFLHc5q4AOawABcoGaFEoshyXm0HEZSDoU0eN3iWyCdBoLDonzAAFEyEhsEJOH1QBx+AByDiUISEFVWMRIISwHjgADKStMnHgDjO1Uu2wG5lQQjk2KYpQceOalEJxJC4RWFLoAwAtKh+HhXCHQDSaJJitircQbWJJZzSbBvaTybtbkpQKcLlcEimhu6CUTAj6yX6swB+U2a0CMsPYA0S0AAdXoatYGKCOr1Brz1oL7HgIv+rncnm8sntaMIOxIsZmPBcbnQ8Duq8nXmoPihMPjidiKQADGlW35FAhmCweJgr-Zx2up6JEm4dgUBMrkJH8Z7rlCpRGJwSpICE8AoNitKvKEXA5LA6r6HQXh2Pw7zIKU4JOsujDMG6f5euWGZVgUDhzBM8DsJgkR0PAbChNwKqmPIQjQJoBg0owIilAASk4ADCSo4Y0Bh5AUsB7IUUmHDheIcOc0DUBwW7oD45yFkkxDwCW-7pr6dQFPENw5qAKkvr45zHmerZSYU7Y8IEYjVLBsrYFMpqEr2xpfvwEx0EEHEdIeVydE+24fKouAIQgsB0F2zRiH0XSem5CRYNMxQgKUCl0K5UwzgwhDpe5rhuO5UxEJo8BbCJzTELIbCEu0BgSJQphAtMoDAu8zZKn8mBIFM2A0EgdjLqUB75tsYwdDVhBNCQDhLscLhDUgkhhHgwXTXcckKUpKk+NtYixK2UBUPNGIyNwTKEC0KA0vKlB2OwcHGMEdHGPYoiPgNz47l1cBcDCKCbNsuylIgRWYBlMnHHtikISpABMakaamuIEWWJL6UihnZrmZk7hZ8SJBj6SgLWazVA2pkTh4xNqVZ56lGUth9T88DU-VrAwGIzWfSBt6sDyKHLSug3AhtW1TWIyO3Jj8mI8p9Oo8dp2szSSENTwfAhh4GluKgHBCHgzDvGgUjwG+gT5HQnGPgQSlhQzVDSKUl5YjA8C-DwrU8M5KDvDYL2OET3j+ERuP+qTRZaaA6SZKoOTEGJ9DFEoQA) that explains why we need `Parameters<BackendOperation> extends []`.

File: waspc/examples/todoApp/src/actions.ts [hunk 8]
```diff
@@ -43,8 +43,8 @@ export const updateTaskIsDone: UpdateTaskIsDone<
   }
 
   // Uncomment to test optimistic updates
-  // const sleep = (ms) => new Promise(res => setTimeout(res, ms))
-  // await sleep(3000);
+  const sleep = (ms: number) => new Promise((res) => setTimeout(res, ms))
+  await sleep(5000)
```
Comment (sodic) [inline waspc/examples/todoApp/src/actions.ts:47]: I'll comment this out after testing.

File: waspc/examples/todoApp/src/Todo.tsx [hunk 9]
```diff
@@ -10,19 +10,42 @@ import {
...
+    const task = await getTask({ id: someId })
+    console.info(`Got task with id ${someId}`, task)
+  }
+
+  const date = await getDate()
+  console.info('Got date:', date)
+
+  const anything = await getAnything()
+  console.info('Got anything:', anything)
+}
```
Comment (sodic) [inline waspc/examples/todoApp/src/Todo.tsx:39]: I'll comment this out after testing.

File: waspc/examples/todoApp/src/pages/Task.tsx
Comment (sodic) [inline waspc/examples/todoApp/src/pages/Task.tsx:1]: Only formatting.

File: waspc/examples/todoApp/src/queries.ts [hunk 10]
```diff
@@ -47,3 +58,11 @@ export const getTask: GetTask<Pick<Task, 'id'>, Task> = async (where, context) =
...
   return new Date()
 }
+
+export const getAnything: GetAnything = async () => {
+  return 'anything'
+}
+
+export const getTrueVoid = (async () => {
+  return 'anything'
+}) satisfies GetTrueVoid
```
Comment (sodic) [inline waspc/examples/todoApp/src/queries.ts:68]: This is all that's new. I've added these Queries to cover all edge cases with my types tests in `TestRpcTypes`.

The rest of the file is formatting.

File: waspc/examples/todoApp/src/App.tsx [hunk 11]
```diff
@@ -1,10 +1,12 @@
...
-import { useQuery, getDate } from "wasp/client/operations";
+import { useSocket } from 'wasp/client/webSocket'
+import { Link } from 'wasp/client/router'
+import { logout, useAuth } from 'wasp/client/auth'
+import { useQuery, getDate } from 'wasp/client/operations'
 
 import './Main.css'
 import { getName } from './user'
+// Necessary to trigger type tests.
+import './TestRpcTypes'
```
Comment (infomiho) [inline waspc/examples/todoApp/src/App.tsx:9]: I'd recommend maybe creating a `type-tests` folder or something like that and then import a `index.ts` from that folder to keep things a bit more organised.

File: waspc/examples/todoApp/src/TestRpcTypes.ts [hunk 12]
```diff
@@ -0,0 +1,112 @@
...
+  getAnything,
+  getTrueVoid,
+} from 'wasp/client/operations'
+import { Task } from 'wasp/entities'
+import { Payload } from 'wasp/server/_types'
+
+// For the details of this specification, see
+// https://github.com/wasp-lang/wasp/pull/1090#discussion_r1159732471
+
+// This should be [],
```
Comment (infomiho) [inline waspc/examples/todoApp/src/TestRpcTypes.ts:21]: Maybe put a TODO here

File: waspc/examples/todoApp/src/App.tsx (hunk 11 above)
Comment (infomiho) [reply waspc/examples/todoApp/src/App.tsx:9]: Then you could put the helpers in `typeTestHelpers` or something like that and then the RPC tests just in its own file.

File: waspc/data/Generator/templates/sdk/wasp/client/operations/queries/index.ts [hunk 13]
```diff
@@ -12,5 +12,5 @@ export const {= operationName =}: QueryFor<{= operationTypeName =}> = createQuer
 )
 {=/ queries =}
 
-// PRIVATE API
-export { addMetadataToQuery } from './core'
+// PRIVATE API (used in SDK)
```
Comment (infomiho) [inline waspc/data/Generator/templates/sdk/wasp/client/operations/queries/index.ts:15]: If used only in SDK, do you need to expose in the `package.json`?

File: waspc/data/Generator/templates/sdk/wasp/client/operations/queries/core.ts [hunk 14]
```diff
@@ -1,53 +1,64 @@
...
-
-// PRIVATE API
-export function addMetadataToQuery(
-  query,
-  { relativeQueryPath, queryRoute, entitiesUsed }
-) {
-  query.queryCacheKey = [relativeQueryPath]
+// PRIVATE API (used in SDK)
+export function buildAndRegisterQuery<Input, Output>(
+  queryFn: ClientOperation<Input, Output>,
```
Comment (infomiho) [inline waspc/data/Generator/templates/sdk/wasp/client/operations/queries/core.ts:40]: How not use `QueryFunction` here?

File: waspc/data/Generator/templates/sdk/wasp/client/operations/queries/core.ts [hunk 15]
```diff
@@ -1,53 +1,64 @@
...
+  { queryCacheKey, queryRoute, entitiesUsed }: 
+  { queryCacheKey: string[], queryRoute: Route, entitiesUsed: string[] }
+): QueryForFunction<typeof queryFn> {
+  const query = queryFn as QueryForFunction<typeof queryFn>
```
Comment (infomiho) [inline waspc/data/Generator/templates/sdk/wasp/client/operations/queries/core.ts:44]: Nice cast

File: waspc/data/Generator/templates/sdk/wasp/client/operations/queries/core.ts [hunk 16]
```diff
@@ -1,53 +1,64 @@
...
+
+  query.queryCacheKey = queryCacheKey 
   query.route = queryRoute
   addResourcesUsedByQuery(query.queryCacheKey, entitiesUsed)
+
+  return query
+
```
Comment (infomiho) [inline waspc/data/Generator/templates/sdk/wasp/client/operations/queries/core.ts:51]: Nit: extra new line

File: waspc/data/Generator/templates/sdk/wasp/client/operations/queries/core.ts [hunk 17]
```diff
@@ -1,53 +1,64 @@
...
+// PRIVATE API (but should maybe be public, users define values of this type)
+export type QueryFor<BackendQuery extends GenericBackendOperation> =
+  QueryForFunction<QueryFunctionFor<BackendQuery>>
+
+type QueryFunctionFor<BackendQuery extends GenericBackendOperation> =
+  OperationRpcFor<BackendQuery>
 
+// PRIVATE API (needed in SDK)
+type QueryForFunction<QF extends QueryFunction<never, unknown>> = 
+  QF & QueryMetadata
```
Comment (infomiho) [inline waspc/data/Generator/templates/sdk/wasp/client/operations/queries/core.ts:63]: I found this block hard to parse, maybe put some _why_ comment on top to make it easier for us in the future to get back into this code.

**Review by infomiho — COMMENTED** [review]
Good stuff! 

I like the cleanup you did, left some minor comments

File: waspc/examples/todoApp/src/actions.ts [hunk 18]
```diff
@@ -43,8 +43,8 @@ export const updateTaskIsDone: UpdateTaskIsDone<
   }
 
   // Uncomment to test optimistic updates
```
[the remark this answers is not in the document]
Comment (sodic) [reply waspc/examples/todoApp/src/actions.ts:45]: Yes, I guess it's better if we keep it. It will make it obvious that optimistic updates are broken. Good call

File: waspc/examples/todoApp/src/Todo.tsx [hunk 19]
```diff
@@ -10,19 +10,42 @@ import {
...
+
 export function areThereAnyTasks(
   tasks: Task[] | undefined
 ): tasks is NonEmptyArray<Task> {
   return !!(tasks && tasks.length > 0)
 }
 
 const Todo = () => {
+  logAll()
```
[the remark this answers is not in the document]
Comment (sodic) [reply waspc/examples/todoApp/src/Todo.tsx:48]: Good idea, but too much work for now (I was going to remove these logs).

I'll definitely create an issue for it though.

File: waspc/data/Generator/templates/sdk/wasp/client/operations/queries/index.ts (hunk 13 above)
Comment (sodic) [reply waspc/data/Generator/templates/sdk/wasp/client/operations/queries/index.ts:15]: No, that's what we'll do as part of #1922.

But for now, yes (since other parts of SDK use it as a package import).

File: waspc/examples/todoApp/src/TestRpcTypes.ts (hunk 12 above)
Comment (sodic) [reply waspc/examples/todoApp/src/TestRpcTypes.ts]: I'll do you one better: https://github.com/wasp-lang/wasp/issues/2004

File: waspc/examples/todoApp/src/TestRpcTypes.ts
Comment (Martinsos) [reply waspc/examples/todoApp/src/TestRpcTypes.ts:1]: Open an issue for it?

**Review by infomiho — APPROVED** [review]
LGTM, make sure that CI is passing successfully

File: waspc/examples/todoApp/src/TestRpcTypes.ts
Comment (sodic) [reply waspc/examples/todoApp/src/TestRpcTypes.ts:1]: We already have one: https://github.com/wasp-lang/wasp/issues/1951

File: waspc/data/Generator/templates/sdk/wasp/client/operations/rpc.ts (hunk 5 above)
Comment (sodic) [reply waspc/data/Generator/templates/sdk/wasp/client/operations/rpc.ts]: Done: https://github.com/wasp-lang/wasp/issues/2020

File: waspc/data/Generator/templates/sdk/wasp/client/operations/rpc.ts (hunk 6 above)
Comment (sodic) [reply waspc/data/Generator/templates/sdk/wasp/client/operations/rpc.ts:42]: Continuation of this whole discussion here: #2017

File: waspc/data/Generator/templates/sdk/wasp/client/operations/hooks.ts [hunk 20]
```diff
@@ -7,91 +7,31 @@ import {
...
   }
 
-  const queryKey =
-    queryFnArgs !== undefined
-      ? [...queryFn.queryCacheKey, queryFnArgs]
-      : queryFn.queryCacheKey;
   return rqUseQuery({
-    queryKey,
-    queryFn: () => queryFn(queryKey, queryFnArgs),
+    queryKey: makeQueryCacheKey(query, queryFnArgs),
```
[the remark this answers is not in the document]
Comment (sodic) [reply waspc/data/Generator/templates/sdk/wasp/client/operations/hooks.ts:29]: Covered here: #2017
