### PR TITLE
Fix email verification hook being called multiple times

### LINKED ISSUE #3407: `onAfterEmailVerified` hook called twice in development
The `onAfterEmailVerified` hook is being triggered twice in development mode when using Wasp's `<VerifyEmailForm />` component, causing duplicate operations (e.g., welcome emails being sent twice).

**Technically this isn't a bug but expected behaviour:** React 18's Strict Mode renders components twice in development to check if components are doing their cleanup correctly. Since `<VerifyEmailForm />` triggers the verification backend endpoint as soon as it's mounted, this results in the request being sent twice in development.

**But it's unexpected for users** and they might think it will happen in production.

### Proposed solution

Implement a similar workaround as was done for the [OAuth component](https://github.com/wasp-lang/wasp/blob/main/waspc/data/Generator/templates/react-app/src/auth/pages/OAuthCallback.tsx#L70-L76) to prevent the backend from being triggered twice in development mode.

Based on https://discord.com/channels/686873244791210014/1438285961225044039/1441432541402763446

### PR DESCRIPTION
**Pull request by infomiho**
## Description

Closes #3407

It makes sure the endpoint is not called twice and updates the Playwright tests to test for that. This is an _okay_ workaround to help users not be confused while developing as to why the `onAfterEmailVerified` is called twice.

## Type of change

- [ ] **🔧 Just code/docs improvement** 
- [x] **🐞 Bug fix** 
- [ ] **🚀 New/improved feature** 
- [ ] **💥 Breaking change** 

## Checklist

- [x] I tested my change in a Wasp app to verify that it works as intended.

- 🧪 Tests and apps:

  - [ ] I added **unit tests** for my change. 
  - [x] _(if you fixed a bug)_ I added a **regression test** for the bug I fixed. 
  - [ ] _(if you added/updated a feature)_ I added/updated **e2e tests** in `examples/kitchen-sink/e2e-tests`.
  - [ ] _(if you added/updated a feature)_ I updated the **starter templates** in `waspc/data/Cli/templates`, as needed.
  - [ ] _(if you added/updated a feature)_ I updated the **example apps** in `examples/`, as needed.
    - [ ] _(if you updated `examples/tutorials`)_ I updated the tutorial in the docs (and vice versa).

- 📜 Documentation:

  - [ ] _(if you added/updated a feature)_ I **added/updated the documentation** in `web/docs/`.

- 🆕 Changelog: _(if change is more than just code/docs improvement)_
  - [x] I updated `waspc/ChangeLog.md` with a **user-friendly** description of the change.
  - [ ] _(if you did a breaking change)_ I added a step to the current **migration guide** in `web/docs/migration-guides/`.
  - [ ] I **bumped the `version`** in `waspc/waspc.cabal` to reflect the changes I introduced.

### CODE REVIEW

File: waspc/data/Generator/templates/sdk/wasp/auth/forms/internal/email/VerifyEmailForm.tsx [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import { useContext, useEffect } from 'react'
```
Comment (infomiho) [inline waspc/data/Generator/templates/sdk/wasp/auth/forms/internal/email/VerifyEmailForm.tsx:1]: The fix is just this file - rest is updating headless and snapshot tests.

File: waspc/data/Generator/templates/sdk/wasp/auth/forms/internal/email/VerifyEmailForm.tsx [hunk 2]
```diff
@@ -34,9 +34,13 @@ export const VerifyEmailForm = () => {
...
 
+  const isFirstRender = useRef(true)
   useEffect(() => {
-    submitForm()
-  }, [location])
+    if (isFirstRender.current) {
+      isFirstRender.current = false
+      submitForm()
+    }
+  }, [])
```
Comment (cprecioso) [inline waspc/data/Generator/templates/sdk/wasp/auth/forms/internal/email/VerifyEmailForm.tsx]: I'll allow it 😂 since we can easily take care of this once we do #3453

File: waspc/ChangeLog.md [hunk 3]
```diff
@@ -2,6 +2,10 @@
 
 ## Next
 
+### 🐞 Bug fixes
+
+- Fixed email verification hook being called multiple times. ([#3458](https://github.com/wasp-lang/wasp/pull/3458))
```
Comment (cprecioso) [inline waspc/ChangeLog.md]: Mmm, same thing as in the other PR, I think we can morph this into something informative for our users who might not have all the context

```suggestion
- Fixed `onAfterEmailVerified` hook being called twice while in development mode. ([#3458](https://github.com/wasp-lang/wasp/pull/3458))
```

File: examples/kitchen-sink/schema.prisma [hunk 4]
```diff
@@ -12,9 +12,10 @@ generator client {
 model User {
   id Int @id @default(autoincrement())
 
-  isOnAfterSignupHookCalled        Boolean @default(false)
-  isOnAfterLoginHookCalled         Boolean @default(false)
-  isOnAfterEmailVerifiedHookCalled Boolean @default(false)
+  isOnAfterSignupHookCalled          Boolean @default(false)
+  isOnAfterLoginHookCalled           Boolean @default(false)
+  isOnAfterEmailVerifiedHookCalled   Boolean @default(false)
+  numTimesOnAfterEmailVerifiedCalled Int     @default(0)
```
Comment (cprecioso) [inline examples/kitchen-sink/schema.prisma:18]: Good thinking!

File: waspc/data/Generator/templates/sdk/wasp/auth/forms/internal/email/VerifyEmailForm.tsx (hunk 2 above)
Comment (sodic) [inline waspc/data/Generator/templates/sdk/wasp/auth/forms/internal/email/VerifyEmailForm.tsx]: Can we have a comment (both here and in the auth component) to explain what's happening and why. Better yet, we could have a custom reusable hook with a nice name. Any comments could then go to its definition.

Also, do we have a long term solution for this? If not, I think we should have an issue for creating one and point to that from the code.

File: examples/kitchen-sink/schema.prisma (hunk 4 above)
Comment (sodic) [reply examples/kitchen-sink/schema.prisma:18]: Do we have the same test for the oauth component. If it's fast, I suggest adding it in. If not, you can skip it.

Comment (infomiho) [reply examples/kitchen-sink/schema.prisma:18]: Don't have any OAuth headless tests because we can't mock Google login yet (same as in #3256) so I can't add this kind of test easily.

File: waspc/data/Generator/templates/sdk/wasp/auth/forms/internal/email/VerifyEmailForm.tsx (hunk 2 above)
Comment (infomiho) [reply waspc/data/Generator/templates/sdk/wasp/auth/forms/internal/email/VerifyEmailForm.tsx]: Long term fix will be upgrading to React 19 and using one of the methods @cprecioso proposed in the issue:
> Suspense or useAction

Extracting this as a reusable hook is a bit tricky since we need it both in the SDK and the web-app. So I'd need to export a new symbol from the SDK for the web-app. I'll see what I can do and report back.

Comment (infomiho) [reply waspc/data/Generator/templates/sdk/wasp/auth/forms/internal/email/VerifyEmailForm.tsx]: Extracted logic into `useEffectOnce` and added the comment there. Updated the public API table.
