### PR TITLE
Fix `validateEnv` plugin when using bundled code

### LINKED ISSUE #3875: Client env validation plugin can depend on bundler before bundling happens
The `validateEnv` plugin (`data/Generator/templates/sdk/wasp/client/vite/plugins/validateEnv.ts`) executes before bundling, but user code where `defineEnvValidationSchema` is defined can still rely on bundler-specific module resolution/features.

 It was due to luck that nobody used the bundler features in the files using the Wasp's `defineEnvValidationSchema` function. If they did, they would error out.

Reproduction:
- go into `src/env.ts` file in the `kitchen-sink` project
- add:
  ```ts
  import * as error from "./cn";
  error.cn("");
  ```
- importing without extension depends on a bundler to work here, and it will error out on `wasp start`:
  Image
- Note: `import * as error from "./cn.js";` would work

How to fix:
- most likely revert the changes here: https://github.com/wasp-lang/wasp/pull/2392

Notes:
- Besides the on-build client env validation above, we also have runtime client env validation. Though, the environment variables are interpolated into the client build files on build. That is why we want to catch errors early.

### PR DESCRIPTION
**Pull request by FranjoMindek**
Fixes: https://github.com/wasp-lang/wasp/issues/3875
Next PR in chain: https://github.com/wasp-lang/wasp/pull/4049

## Description

Our current `validateEnv.ts` plugin directly imports the `clientEnvSchema` from the SDK.
In SDK, `clientEnvSchema`'s module imports the user's client env schema (from e.g. `src/env.ts` in `kitchen-sink` in example below).

The problem is that the user code can depend on bundler features (notice the extensionless import), and the plugin is resolved before any bundling is done.

The fix is to make the plugin use the `ViteDevServer` to bundle the necessary modules for us. When using `vite serve`, we can use the existing `server` and load the module, otherwise for `vite build` we have to start our own `server`.

| Before change - crashes | After change - works |
| ------------- | ------------- |
| image  | image  |

This PR also change how the validate env plugin works. Now it fails fast, before the client can render in the browser, and the validation message is logged in console. We piggyback on the existing validation mechanism in the SDK's `client/env.ts` file.

image

That means we won't display the env validation error in the browser, but rather we will fail before that. Fails on both `wasp start` (`vite serve`) and `wasp build start` (`vite build`).

## Type of change

- [ ] **🔧 Just code/docs improvement** 
- [x] **🐞 Bug fix** 
- [ ] **🚀 New/improved feature** 
- [ ] **💥 Breaking change** 

## Checklist

- [x] I tested my change in a Wasp app to verify that it works as intended.

- 🧪 Tests and apps:

  - [ ] I added **unit tests** for my change. 
  - [ ] _(if you fixed a bug)_ I added a **regression test** for the bug I fixed. 
  - [ ] _(if you added/updated a feature)_ I added/updated **e2e tests** in `examples/kitchen-sink/e2e-tests`.
  - [ ] _(if you added/updated a feature)_ I updated the **starter templates** in `waspc/data/Cli/templates`, as needed.
  - [ ] _(if you added/updated a feature)_ I updated the **example apps** in `examples/`, as needed.
    - [ ] _(if you updated `examples/tutorials`)_ I updated the tutorial in the docs (and vice versa).

- 📜 Documentation:

  - [ ] _(if you added/updated a feature)_ I **added/updated the documentation** in `web/docs/`.

- 🆕 Changelog: _(if change is more than just code/docs improvement)_
  - [x] I updated `waspc/ChangeLog.md` with a **user-friendly** description of the change.
  - [ ] _(if you did a breaking change)_ I added a step to the current **migration guide** in `web/docs/migration-guides/`.
  - [ ] I **bumped the `version`** in `waspc/waspc.cabal` to reflect the changes I introduced.

### CODE REVIEW

File: waspc/data/Generator/templates/sdk/wasp/client/env/schema.ts [hunk 1]
```diff
@@ -28,12 +28,12 @@ const waspProdClientEnvSchema = z.object({
   "{= serverUrlEnvVarName =}": serverUrlSchema,
 });
 
+const waspClientEnvSchema = import.meta.env.MODE === "production"
```
Comment (FranjoMindek) [inline waspc/data/Generator/templates/sdk/wasp/client/env/schema.ts:31]: Since we always load this module through vite, this will always be valid.

File: waspc/data/Generator/templates/sdk/wasp/client/vite/plugins/validateEnv.ts [hunk 2]
```diff
@@ -1,54 +1,111 @@
...
-      // Exit if we are in build mode, because we can't show the error in the browser.
-      if (config.command === "build" && !validationResult.success) {
-        const validationErrorMessage = formatZodEnvError(validationResult.error);
-        console.error(colorize("red", validationErrorMessage));
-        process.exit(1);
+
+      const tempServer = await createViteServer({
+        root: resolvedConfig.root,
+        mode: resolvedConfig.mode,
+        configFile: false,
```
Comment (FranjoMindek) [inline waspc/data/Generator/templates/sdk/wasp/client/vite/plugins/validateEnv.ts:36]: We must not read the `configFile` file to set the plugin list ourselves.
Possible point of divergence.

File: waspc/data/Generator/templates/sdk/wasp/client/vite/plugins/validateEnv.ts [hunk 3]
```diff
@@ -1,54 +1,111 @@
...
+          this.error(colorize("red", validationErrorMessage));
+        }
+      } finally {
+        await tempServer.close();
       }
     },
-    configureServer: (server) => {
-      if (validationResult === null || validationResult.success) {
+
+    async configureServer(server) {
```
Comment (FranjoMindek) [inline waspc/data/Generator/templates/sdk/wasp/client/vite/plugins/validateEnv.ts]: It seems like we crash due to `client/env.ts`:
```ts
export const env = ensureEnvSchema(
  import.meta.env,
  clientEnvSchema,
);
```
before we can send a message to the client here. 
Might be related to SSR changes?

If so either fix or drop this path?

File: waspc/data/Generator/templates/sdk/wasp/client/vite/plugins/validateEnv.ts [hunk 4]
```diff
@@ -1,54 +1,62 @@
...
-export function validateEnv(): Plugin {
-  let validationResult: ReturnType<typeof getValidatedEnvOrError> | null = null;
+  type Plugin,
+  type PluginOption,
+  type ResolvedConfig,
+  createServer as createViteServer,
+  isRunnableDevEnvironment
+} from "vite";
+
+const CLIENT_ENV_SCHEMA_VALIDATION_MODULE = "wasp/client";
```
Comment (cprecioso) [inline waspc/data/Generator/templates/sdk/wasp/client/vite/plugins/validateEnv.ts]: This seems like a very generic entrypoint that could be importing fifty other things. Should we create a more scoped `wasp/client/validate-env` or something like that?

Comment (FranjoMindek) [reply waspc/data/Generator/templates/sdk/wasp/client/vite/plugins/validateEnv.ts]: Can be done, but if we add anything it becomes public.
Alternative is to try to do abs path to the `client/env.ts` file.

Comment (sodic) [reply waspc/data/Generator/templates/sdk/wasp/client/vite/plugins/validateEnv.ts]: > Alternative is to try to do abs path to the client/env.ts file.

I'm guessing you mean relative? Yes, that's what we should do :)

File: waspc/data/Generator/templates/sdk/wasp/client/env/schema.ts [hunk 5]
```diff
@@ -28,12 +28,12 @@ const waspProdClientEnvSchema = z.object({
...
+  ? waspProdClientEnvSchema
+  : waspDevClientEnvSchema;
+
 // PRIVATE API (sdk, Vite config)
-// TODO(franjo): Remove passing mode as param when this is no longer a plugin.
```
Comment (sodic) [inline waspc/data/Generator/templates/sdk/wasp/client/env/schema.ts:32]: Where did we un-register this as a plugin? Or is it still a plugin?

**Review by sodic — COMMENTED** [review]
We discussed this in person. Conclusions:
- Do more research into other frameworks.
- Decide what we're trading off and what's necessary.
- If it stays like this, consolidate the approaches (unless it's a perf issue).
- Document the reasons and constraints in the code.

**Comment by FranjoMindek** [comment]
> We discussed this in person. Conclusions:
> 
>     * Do more research into other frameworks.

Nodbody really does it like us, so no existing example to follow. 
Whats unavoidable for our approach:
- Client env schema validation depends on bundler features.

>     * Decide what we're trading off and what's necessary.
>     * If it stays like this, consolidate the approaches (unless it's a perf issue).

We can:
1) Resolve the module through an existing Vite server
   - Works only on `serve` through `configureServer`
   - GOOD: Very easy and straightforward, import the `client/env.ts` to trigger the validation side-effect.
2) Create additional client env schema validation build artifact which we execute post build 
   - Works only on `build`.
   - BAD: Executes after artifacts are already created.
   - BAD: To stop bad deployments we need to cleanup the artifacts.
3) Create a separate Vite server which shares the same module resolution as the user's Vite server. Resolve the module though it. 
   - Works on both `serve` and `build`.
   - GOOD: Logic is the same as the first approach.
   - BAD: Requires spinning a separate server.

I would discard approach 2) as I would like to warn the users about bad environment variables as soon as possible. So performance wise the ideal solution would be to pick approach 1) for `serve` and approach 3) for `build`.

I wanted to test how large the performance difference is during `serve` is between 1) and 3). I got the following times for total plugin execution time:
Approach 1) ~ 50ms
Approach 3) ~ 75ms 

Because of that I think that sticking to approach 3) for both `serve` and `build` works the best.
   
However, should users report a noticeable slowdown on `wasp start` we should evaluate this once again.

NOTE: `buildStart` hook we use in the solution triggers only once during `wasp start`. Users will have to restart `wasp start` if they change their "`env.ts`" file to pick up the changes. The fix is to implement HMR handler for the plugin, which brings us back to the `configureServer` hook.

File: waspc/data/Generator/templates/sdk/wasp/client/env/schema.ts (hunk 5 above)
Comment (FranjoMindek) [reply waspc/data/Generator/templates/sdk/wasp/client/env/schema.ts:32]: Still is.

File: waspc/src/Wasp/Generator/SdkGenerator/Client/VitePluginG.hs [hunk 6]
```diff
@@ -104,3 +105,12 @@ genDetectServerImportsPlugin = return $ C.mkTmplFdWithData tmplPath tmplData
...
     tmplData = object ["srcDirInWaspProjectDir" .= SP.fromRelDir srcDirInWaspProjectDir]
+
+gebValidateEnvPlugin :: Generator FileDraft
+gebValidateEnvPlugin = return $ C.mkTmplFdWithData tmplPath tmplData
+  where
+    tmplPath = C.vitePluginsDirInSdkTemplatesDir </> [relfile|validateEnv.ts|]
+    tmplData = object ["clientEnvSchemaValidationModulePath" .= clientEnvSchemaValidationModulePath]
+
+    clientEnvSchemaValidationModulePath = SP.fromRelFileP . fromJust . SP.relFileToPosix $ clientEnvSchemaValidationModuleDir
+    clientEnvSchemaValidationModuleDir = generatedAppDirInWaspProjectDir </> C.sdkRootDirInGeneratedAppDir </> [relfile|client/env.ts|]
```
Comment (FranjoMindek) [inline waspc/src/Wasp/Generator/SdkGenerator/Client/VitePluginG.hs:116]: Hard to connect the latter path of the path.
At least the `validateEnv` plugin will crash the `wasp start` immediately due to unknown resolution if we ever change the path of the module and don't update it here.

I.e. the tests will catch it.

File: waspc/data/Generator/templates/sdk/wasp/client/vite/plugins/validateEnv.ts (hunk 2 above)
Comment (sodic) [reply waspc/data/Generator/templates/sdk/wasp/client/vite/plugins/validateEnv.ts:36]: Where are we setting the plugin list ourselves? I don't see that.

Also, when there's duplication, we should point from one place to the other, like this: https://github.com/wasp-lang/wasp/blob/main/.nvmrc

File: waspc/data/Generator/templates/sdk/wasp/client/vite/plugins/validateEnv.ts [hunk 7]
```diff
@@ -1,54 +1,61 @@
...
+      const tempServer = await createViteServer({
+        root: resolvedConfig.root,
+        mode: resolvedConfig.mode,
+        // To ensure we pick up all user-defined plugins (resolution matches the main build)
+        // while avoiding recursion. This includes the `wasp` plugin.
+        configFile: false,
+        plugins: resolvedConfig.plugins.filter(
+          (plugin) => plugin.name !== PLUGIN_NAME
+        ),
+        // Minimize the possible server side-effects.
```
Comment (sodic) [inline waspc/data/Generator/templates/sdk/wasp/client/vite/plugins/validateEnv.ts]: What does this mean? We should elaborate.

File: waspc/data/Generator/templates/sdk/wasp/client/vite/plugins/validateEnv.ts [hunk 8]
```diff
@@ -1,54 +1,61 @@
...
 
-      // Exit if we are in build mode, because we can't show the error in the browser.
-      if (config.command === "build" && !validationResult.success) {
-        const validationErrorMessage = formatZodEnvError(validationResult.error);
-        console.error(colorize("red", validationErrorMessage));
-        process.exit(1);
+      try {
+        if (!isRunnableDevEnvironment(tempServer.environments.ssr)) {
+          throw new Error(`Expected ssr to be a runnable dev environment`)
+        }
```
Comment (sodic) [inline waspc/data/Generator/templates/sdk/wasp/client/vite/plugins/validateEnv.ts:57]: This needs an explanation too.

**Review by sodic — APPROVED** [review]
Looks ok assuming we go this route. But please add the comments I requested.

File: waspc/data/Generator/templates/sdk/wasp/client/vite/plugins/validateEnv.ts (hunk 2 above)
Comment (FranjoMindek) [reply waspc/data/Generator/templates/sdk/wasp/client/vite/plugins/validateEnv.ts:36]: just below?
```ts
plugins: resolvedConfig.plugins.filter(
  (plugin) => !PLUGINS_TO_SKIP_IN_TEMP_VITE_SERVER.has(plugin.name),
),
```

Comment (FranjoMindek) [reply waspc/data/Generator/templates/sdk/wasp/client/vite/plugins/validateEnv.ts:36]: In vite, the `plugins` field would add additional fields on top of those already resolved through the vite config. It's not replacement, its addition.

To fully control the plugin list, we insert the user plugins ourselves, through the already resolved config.

> Possible point of divergence
 
Since we set the field values ourselves, rather than reading them from the user's vite config.
I wonder if we should do `...resolvedConfig` at the top and then override what we need instead. Most likely not.
