### PR TITLE
Handle multiple existing domains for Railway deployment

### LINKED ISSUE #3581: Handle multiple existing domains parsing for Railway deployment
**Describe the bug**
```
Build time: 98.59 seconds
Deploy complete
🚀 Server has been deployed!
🚀 Deploying your client now...
$ railway domain --service <project-name>-server --port 8080 --json
Domains already exist on the service:
- https://api.<domain>
- https://<project-id>-server-production.up.railway.app
🚀 Unexpected token 'D', "Domains al"... is not valid JSON


❌ --- [Error] Deploy command failed: ---------------------------------------------

Deploy command failed with exit code: 1
```

We are not parsing the multi-line output when there are multiple existing domains. 

Reported by user: https://discord.com/channels/686873244791210014/1458081883827994809/1458081883827994809

**To Reproduce**

1. Deploy a project to Railway via Wasp CLI
2. Add custom domain to the server
3. Re-try deploying the project via Wasp CLI

**Expected behavior**
Detecting existing domains should work even if there are multiple domains for a service. Ideally, we'd resolve selecting the server domain out of the multiple available.

**Additional context**
Confirmed on Wasp version 0.17.0 - we still need to reproduce it with Wasp 0.20.0

### PR DESCRIPTION
**Pull request by cprecioso**
- Resolves #3581

## Description

This PR adds support for handling multiple domains returned by Railway CLI (>=4.18.1) while maintaining backward compatibility with older versions. It also makes the **existing** logic to select a custom domain explicit instead of implicit.

<details>
<summary><b>Gallery</b></summary>

<table>
<tr>
 <td>Multiple domains, default behaviour
 <td>Screenshot 2026-01-27 at 17 30 40
<tr>
 <td>Multiple domains, selecting a non-existing one with `REACT_APP_API_URL`
 <td>image
<tr>
 <td>Multiple domains, selecting a correct one with `REACT_APP_API_URL`
 <td>image
</table>

</details>

## Type of change

- [ ] **🔧 Just code/docs improvement** 
- [x] **🐞 Bug fix** 
- [ ] **🚀 New/improved feature** 
- [ ] **💥 Breaking change** 

## Checklist

- [x] I tested my change in a Wasp app to verify that it works as intended.

- 🧪 Tests and apps:

  - [ ] I added **unit tests** for my change. 
  - [ ] _(if you fixed a bug)_ I added a **regression test** for the bug I fixed. 
  - [ ] _(if you added/updated a feature)_ I added/updated **e2e tests** in `examples/kitchen-sink/e2e-tests`.
  - [ ] _(if you added/updated a feature)_ I updated the **starter templates** in `waspc/data/Cli/templates`, as needed.
  - [ ] _(if you added/updated a feature)_ I updated the **example apps** in `examples/`, as needed.
    - [ ] _(if you updated `examples/tutorials`)_ I updated the tutorial in the docs (and vice versa).

- 📜 Documentation:

  - [ ] _(if you added/updated a feature)_ I **added/updated the documentation** in `web/docs/`.

- 🆕 Changelog: _(if change is more than just code/docs improvement)_
  - [x] I updated `waspc/ChangeLog.md` with a **user-friendly** description of the change.
  - [ ] _(if you did a breaking change)_ I added a step to the current **migration guide** in `web/docs/migration-guides/`.
  - [ ] I **bumped the `version`** in `waspc/waspc.cabal` to reflect the changes I introduced.

### CODE REVIEW

File: waspc/data/packages/deploy/src/providers/railway/jsonOutputSchemas.ts [hunk 1]
```diff
@@ -23,8 +23,15 @@ export const RailwayCliProjectSchema = z.object({
...
-});
+export const RailwayCliDomainSchema = z.union([
+  // Railway CLI >=4.18.1
+  z.object({ domains: z.array(z.string()).min(1) }),
+
+  // Railway CLI <4.18.1
+  z
+    .object({ domain: z.string() })
+    // Convert to the newer format
+    .transform(({ domain }) => ({ domains: [domain] })),
```
Comment (infomiho) [inline waspc/data/packages/deploy/src/providers/railway/jsonOutputSchemas.ts:34]: Beautiful

**Comment by cprecioso** [comment]
I'll do that in a new PR :)
