### PR TITLE
Fix error swallowing in db reset and db seed

### LINKED ISSUE #3348: Wasp CLI Command `wasp db seed` does not properly propagate the exit codes
When failing inside of the Typescript portion of the `wasp db seed` command execution, we return a exit code of 0 instead of 1.

### How I initially found out about it:

By calling `wasp db seed` with a valid seed name e.g. `devSeedSimple`
```ts
// main.wasp  
db: {
    seeds: [
      import { devSeedSimple } from "@src/features/db/seeds",
      import { prodSeed } from "@src/features/db/seeds"
    ],
    prismaSetupFn: import { setUpPrisma } from "@src/features/db/prisma",
  },
```
But not actually exporting the declared function, we error out on `wasp db seed` but return exit code 0:

Image

### Easy reproduction

Same can be done by throwing any `Error` inside of the seed function:
```ts
export const devSeedSimple: DbSeedFn = async (prismaClient) => {
  throw Error("AAAA");
}
```

Image

### Extra context I checked for now

Calling the seed directly from `package.json` script (`npm run db-seed`) inside of `.wasp/out/server` returns 1 properly:

Image

### PR DESCRIPTION
**Pull request by sodic**
## Description

Fixes #3348.

## Type of change

- [ ] **🔧 Just code/docs improvement** 
- [x] **🐞 Bug fix** 
- [ ] **🚀 New/improved feature** 
- [ ] **💥 Breaking change** 

## Checklist

- [x] I tested my change in a Wasp app to verify that it works as intended.

- 🧪 Tests and apps:

  - [ ] I added **unit tests** for my change.
    - The modified function isn't unit-tested. Adding tests is tricky (thanks to IO) and would blow through the estimate.
  - [ ] _(if you fixed a bug)_ I added a **regression test** for the bug I fixed.
     - Same reason as above.
  - [ ] _(if you added/updated a feature)_ I added/updated **e2e tests** in `examples/kitchen-sink/e2e-tests`.
  - [ ] _(if you added/updated a feature)_ I updated the **starter templates** in `waspc/data/Cli/templates`, as needed.
  - [ ] _(if you added/updated a feature)_ I updated the **example apps** in `examples/`, as needed.
    - [ ] _(if you updated `examples/tutorials`)_ I updated the tutorial in the docs (and vice versa).

- 📜 Documentation:

  - [ ] _(if you added/updated a feature)_ I **added/updated the documentation** in `web/docs/`.

- 🆕 Changelog: _(if change is more than just code/docs improvement)_
  - [x] I updated `waspc/ChangeLog.md` with a **user-friendly** description of the change.
  - [ ] _(if you did a breaking change)_ I added a step to the current **migration guide** in `web/docs/migration-guides/`.
  - [ ] I **bumped the `version`** in `waspc/waspc.cabal` to reflect the changes I introduced.
    - I updated it in a different PR that's getting merged soon, no reason to cause conflicts.

### CODE REVIEW

File: waspc/cli/src/Wasp/Cli/Command/Db/Seed.hs [hunk 1]
```diff
@@ -36,7 +36,7 @@ seed maybeUserProvidedSeedName = do
   cliSendMessageC $ Msg.Start $ "Running database seed " <> nameOfSeedToRun <> "..."
 
   liftIO (dbSeed genProjectDir nameOfSeedToRun) >>= \case
-    Left errorMsg -> cliSendMessageC $ Msg.Failure "Database seeding failed" errorMsg
```
Comment (sodic) [inline waspc/cli/src/Wasp/Cli/Command/Db/Seed.hs:39]: This is where the old code was swallowing errors. We'd just output a failure message and continue as if nothing happened.

File: waspc/cli/src/Wasp/Cli/Command/Db/Reset.hs [hunk 2]
```diff
@@ -21,5 +22,5 @@ reset = do
   cliSendMessageC $ Msg.Start "Resetting the database..."
 
   liftIO (dbReset genProjectDir) >>= \case
-    Left errorMsg -> cliSendMessageC $ Msg.Failure "Database reset failed" errorMsg
```
Comment (sodic) [inline waspc/cli/src/Wasp/Cli/Command/Db/Reset.hs:24]: This command had the same problem. I tested to confirm happens and fixed it.
