### PR TITLE
Fixes realworld auth error return and display

### LINKED ISSUE #567: [examples/realworld] Updating password bug
Attempting to update your password with a string that does not satisfy all (e.g., does not have a number) results in a `500` error and does not tell the user why the update failed. We should:
- Handle this on the server without breaking
- Inform the user about password requirements
- Think of a way to provide Wasp support for the common password changing procedure

For closing this issue, it's enough to implement the first two points :)

### PR DESCRIPTION
**Pull request by shayneczyzewski**
# Description

This change fixes the 500 return for auth errors when updating the User model. There are other cases we can probably handle better in the future, however, including introducing a pattern to more easily apply these checks themselves.

Fixes #567 

## Type of change

Please select the option(s) that is more relevant.

- [ ] Code cleanup
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### CODE REVIEW

File: examples/realworld/ext/auth/SignupPage.js [hunk 1]
```diff
@@ -4,6 +4,8 @@ import { useHistory } from 'react-router-dom'
 import login from '@wasp/auth/login'
 import signup from '@wasp/auth/signup'
 
+import { errorMessage } from '@wasp/utils.js'
```
Comment (Martinsos) [inline examples/realworld/ext/auth/SignupPage.js:7]: This his not part of the Wasp JS API, right? That is a bit tricky!

File: examples/realworld/ext/user/actions.js [hunk 2]
```diff
@@ -1,20 +1,32 @@
 import HttpError from '@wasp/core/HttpError.js'
+import AuthError from '@wasp/core/AuthError.js'
+import { isPrismaError, prismaErrorToHttpError } from '@wasp/utils.js'
```
Comment (Martinsos) [inline examples/realworld/ext/user/actions.js:3]: What is tricky is that these are not part of documented Wasp JS API, right?

prismaErrorToHttpError -> that I think we want to make part of public Wasp JS API. Maybe also isPrismaError?

File: examples/realworld/ext/user/actions.js [hunk 3]
```diff
@@ -1,20 +1,32 @@
...
+        ...(newPassword ? { password: newPassword } : {})
+      }
+    })
+  } catch (e) {
+    if (e instanceof AuthError) {
+      throw new HttpError(422, 'Validation failed', { message: e.message })
+    } else if (isPrismaError(e)) {
+      throw prismaErrorToHttpError(e)
+    } else {
+      throw new HttpError(500)
```
Comment (Martinsos) [inline examples/realworld/ext/user/actions.js:27]: I think here we can even just rethrow the old error -> there will be part of Wasp that will then ensure to convert it into HttpError 500.

**Review by Martinsos — COMMENTED** [review]
Nice job figuring this out @shayneczyzewski !

I think the current solution is good, except for the issue that some of the stuff we are importing from `@wasp` is not documented. So we need to figure out if we want to document it, and if so, document it, and only then use it.

For example, `errorMessage` -> hm, what is that? Should it be documented? Sounds like maybe it shouldn't?

prismaErrorToHttpError, isPrismaError -> well those sound helpful enough that maybe we would want to expose/document those. Not 100% sure though.

As to how to make this more dry -> well, the `if AuthError else ifPrisma else ...` already sounds pretty specific for this use case, I am having a bit of hard time imagining externalizing that as part of Wasp JS API, doesn't sound general enough.

But, what we could do, is say that Wasp app behaves in such way that is any prisma error makes it to the edge of the app, Wasp automatically converts it into HTTP error. Actually no, scratch this, that would ruin the whole idea of not forwarding errors unless developer explicitly states they want to forward them.

Maybe there is another way to make it DRYer?

File: examples/realworld/ext/user/actions.js (hunk 2 above)
Comment (shayneczyzewski) [reply examples/realworld/ext/user/actions.js:3]: I added them to the docs below @Martinsos, please let me know if that is what you had in mind. Thanks!

File: examples/realworld/ext/auth/SignupPage.js (hunk 1 above)
Comment (shayneczyzewski) [reply examples/realworld/ext/auth/SignupPage.js]: True! I removed that since it wasn't particularly good and just made a local helper version. Thanks 👍🏻

File: web/docs/language/features.md [hunk 4]
```diff
@@ -667,6 +667,35 @@ const Main = () => {
 export default Main
 ```
 
+### Prisma and Validation Error Helpers
+In your Actions, you may wish to handle User entity validation errors or general Prisma errors with HTTP friendly responses. We have exposed one class and two helpers functions for this purpose.
```
Comment (Martinsos) [inline web/docs/language/features.md:671]: Looks good! Maybe you could explicitely say what we expose `AuthError`, `isPrismaError` and `prismaErrorToHttpError`? I know it is a bit redundant, due to code blocks below, but I think it makes it more obvious what is it that we are exposing?

Comment (Martinsos) [reply web/docs/language/features.md:671]: Also, I wonder if we should split these into two sections, one being `prisma errors helpers`, and another `auth error`? They are not really that connected, right? We can actually then talk about `AuthError` in the part of docs where we are explaining authentication, and on the other hand talk about prisma error helpers at the place where we talk about using prisma in Operations -> yes, notice also that you said `Actions`, but it can also be in `Queries` that we get Prisma errors, so you should rather say `Operations`.

File: examples/realworld/ext/user/actions.js (hunk 2 above)
Comment (Martinsos) [reply examples/realworld/ext/user/actions.js:3]: Yup that is it! Just left some comments on how to possibly split those a bit.

File: web/docs/language/features.md (hunk 4 above)
Comment (shayneczyzewski) [reply web/docs/language/features.md:671]: Hey there, sure thing I can refer to them directly, split them into two sections, move auth up, and change other to ops! Will do today 👍🏻 Thanks

Comment (Martinsos) [reply web/docs/language/features.md:671]: Awesome, if you think that is useful let's do it :D!

Comment (shayneczyzewski) [reply web/docs/language/features.md]: Just updated like so 🚀 Good idea, thanks
Screenshot 2022-04-20 122314
Screenshot 2022-04-20 122814

**Review by Martinsos — APPROVED** [review]
Looking great :)!
